apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
type: Opaque
stringData:
  BOT_TOKEN: ENC[AES256_GCM,data:9ixQyt32rVvkuUjVhrUi3OTl1ZKAjS07dDoVbuD8+P5SHnqJNurYBptyY96Viw==,iv:uQqKgFFrDpJ6MU0YJcko0fSHu7vEFvUfrRDajK6Mcew=,tag:olZacmFX1Sre86ST9yGyhw==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N25HZzl4MUdyM3p2RFBC
        TVpPZk0xa0FyMzRjK2RMV1lxS2w1VXNxVWdrCmtMb2ttMkpoaThSNFRrUnM0SVUv
        MzNoMTNwd0h5cTJGMGR5UFY3WFdmQmcKLS0tIGRiVHJHNG9Bczl2NFkwZU1EeHhh
        MFJwbWhzdE9ZNlFoZjRQbFBYenBySmcKDJtumfEyn5lVtiKcgguAYc68VtvV8Jd1
        +24j1xxdWNiUNV8P3hC2gMXQETDF06MVHwAVVG5P+bNCLSIQSWtYtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T01:43:17Z"
  mac: ENC[AES256_GCM,data:0NjgmkjR4foFavxTtbpyYGl+zGJvjxI8+LrsZ9RgyB/d8xZeOOkli/t6OsDO5/1S1Tf4fgE9zHHezgGrpDQErbx9Ofkum+tLFQa+aWTVjX2RHmBM/x4eMN+Z0inxsQyLln4c5nNszHbomotYzj3sA5o667ASmbBuYbcSKfvEUg8=,iv:A5KYzuqs7KWv/Y5aRYJFSj8SOS5u/FmPl6CzubQr8tQ=,tag:TYyVSy2gizYz7RO7pTmyDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: youtube-cookies-secret
type: Opaque
stringData:
  YOUTUBE_EMAIL: ENC[AES256_GCM,data:+sMpCf4WlKeDhJ2wJXyK4iCmPjrYol0=,iv:0lk/81DfqL+6mRrUgTF1WDCuvIZ85xDaByK+GEzrgus=,tag:BAxZKTWG1Y4b2Oe8ULnoKw==,type:str]
  YOUTUBE_PASSWORD: ENC[AES256_GCM,data:UKu2Q6jK6TYoERyX1B8=,iv:k5VDetjkTpgSG/oSJp4jp+r8Xjs6Nrl2NnmoMkWB5cA=,tag:6ptjIKx+s8CDQo+t1Wauog==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N25HZzl4MUdyM3p2RFBC
        TVpPZk0xa0FyMzRjK2RMV1lxS2w1VXNxVWdrCmtMb2ttMkpoaThSNFRrUnM0SVUv
        MzNoMTNwd0h5cTJGMGR5UFY3WFdmQmcKLS0tIGRiVHJHNG9Bczl2NFkwZU1EeHhh
        MFJwbWhzdE9ZNlFoZjRQbFBYenBySmcKDJtumfEyn5lVtiKcgguAYc68VtvV8Jd1
        +24j1xxdWNiUNV8P3hC2gMXQETDF06MVHwAVVG5P+bNCLSIQSWtYtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T01:43:17Z"
  mac: ENC[AES256_GCM,data:0NjgmkjR4foFavxTtbpyYGl+zGJvjxI8+LrsZ9RgyB/d8xZeOOkli/t6OsDO5/1S1Tf4fgE9zHHezgGrpDQErbx9Ofkum+tLFQa+aWTVjX2RHmBM/x4eMN+Z0inxsQyLln4c5nNszHbomotYzj3sA5o667ASmbBuYbcSKfvEUg8=,iv:A5KYzuqs7KWv/Y5aRYJFSj8SOS5u/FmPl6CzubQr8tQ=,tag:TYyVSy2gizYz7RO7pTmyDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: youtube-api-secret
type: Opaque
stringData:
  YOUTUBE_API_KEY: ENC[AES256_GCM,data:YfHdrrDUBV7stda7b6BngqHHKDX7S1UdX5ugseHOcuQbvNPO8nfV,iv:iA93UpLUH7Uzc9Yx2eMS+X6mEVieUv4G4XxwiDP669s=,tag:SODDu5Te5RR79PFLWKVVZA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N25HZzl4MUdyM3p2RFBC
        TVpPZk0xa0FyMzRjK2RMV1lxS2w1VXNxVWdrCmtMb2ttMkpoaThSNFRrUnM0SVUv
        MzNoMTNwd0h5cTJGMGR5UFY3WFdmQmcKLS0tIGRiVHJHNG9Bczl2NFkwZU1EeHhh
        MFJwbWhzdE9ZNlFoZjRQbFBYenBySmcKDJtumfEyn5lVtiKcgguAYc68VtvV8Jd1
        +24j1xxdWNiUNV8P3hC2gMXQETDF06MVHwAVVG5P+bNCLSIQSWtYtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T01:43:17Z"
  mac: ENC[AES256_GCM,data:0NjgmkjR4foFavxTtbpyYGl+zGJvjxI8+LrsZ9RgyB/d8xZeOOkli/t6OsDO5/1S1Tf4fgE9zHHezgGrpDQErbx9Ofkum+tLFQa+aWTVjX2RHmBM/x4eMN+Z0inxsQyLln4c5nNszHbomotYzj3sA5o667ASmbBuYbcSKfvEUg8=,iv:A5KYzuqs7KWv/Y5aRYJFSj8SOS5u/FmPl6CzubQr8tQ=,tag:TYyVSy2gizYz7RO7pTmyDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
