---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clawdbot

components:
  - ../../components/sops

resources:
  - namespace.yaml
  - secrets.sops.yaml
  - clawdbot-gateway/ks.yaml
