apiVersion: v1
kind: Secret
metadata:
  name: clawdbot-secrets
  namespace: clawdbot
type: Opaque
stringData:
  #ENC[AES256_GCM,data:a8lV9MgFaCoWDMCn0XB87AxW/BjYXLq9EwlvCCtpihGJqeuCzu2iEzxSy6npaatN3U8Thf97IraRm+jwHg/Ck6m7By7ZjQ==,iv:7Nd7LyYjtEmQVTGYyuM61m3a/o3oWRVI72Cht6YjVuM=,tag:ccvnN/pq2ri4G1+3obnNug==,type:comment]
  #ENC[AES256_GCM,data:I9DNIMkmQWAQvMDWdbQ48iXiaz0XWRJd/Z7wwQX+,iv:rfLtCe56uSNi+QRGDJHe9uM2Aw4ByJ9azLvJzsPP6NE=,tag:kpdj+FnHegxm2uVxCWIkJw==,type:comment]
  #ENC[AES256_GCM,data:40yDNKo5/oXrgPFh3D4rtBFTMNHut9GW2QgJHFOr7LKFNsiMUGKshzeqGy8rCx1vaX4=,iv:f/GD3dk8pnjdf+HxmLav/v1sM4EYtr2kgHSVKXs81Ts=,tag:knvkfIJAirA9vc6VgOplPA==,type:comment]
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:bb14cDFuwQSY7Cq8CzB7wzjVTdUvG3lRAe7jg0COLwBeQy4WRzN62GxMBAocJQ==,iv:MmWsC878kKjynwNxlG/HqGcuk9YdDBWohAGHAjQaILk=,tag:fAWCs/nrqBGlb1iiOiNnCw==,type:str]
  #ENC[AES256_GCM,data:t6AOuVm/ZAToaCrJGCmBl+deIwQnISKXKn6nKZBibBN0ntKOy1CA5fd6f3A=,iv:RK7jC9DehhNeQwJQPJ8QJxt/Yd06Dulj6N/jmiTI8W0=,tag:i26U6mZyRuaOovCjvsnGRA==,type:comment]
  #ENC[AES256_GCM,data:WxcFE43witLkhVOWmwW1W5rdFFOgcte+n0JHO3ogQTHgDyES2A==,iv:iUeTBRg1+K+l1SiTFBtGwjrAxGeqOal3TbvA7P6oHrs=,tag:ot8fByWHlV+x8i7yvhAZ1w==,type:comment]
  #ENC[AES256_GCM,data:HyGOqmFhH2bdglVG5sgkCh7ZOMyzGwa+8bR3eSk=,iv:8qxakBODOlO0P5DHuWehUzhTxF9QckjaROh4g8OUoCM=,tag:rGuBSRWal9nX+OiInXkWHQ==,type:comment]
  BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:P6faizx6jQ7sgolvyWelRqpki+c2L62Hq1hl+UgKgw==,iv:Ms0VWSWa2KIEct9dXLPRkKY50wXu7Tr8WC+YZE5e6xQ=,tag:2NGBKc+0U10u4cDZOgVQLg==,type:str]
  #ENC[AES256_GCM,data:PzFefbvwVp7poP2dshw/c9kKzFijKzgdy/lq9dq7E5lL1ZfArdzgbqx62w==,iv:JHJV0Lt1ZjGuRWsp8itjLHmSgmbXhNXon2LkXtuPtVM=,tag:vBfGI4lS6X5QEPpCSdQE9Q==,type:comment]
  #ENC[AES256_GCM,data:Je1jjfcXm6g19VbGn76jUWbNXAZKwAo3bqqnHws941ZEdgfNaRM1XWVggH3RHB2Hq/qKlw==,iv:va7hd0vGVQkW3C6O8omZAIWLrigwQpRt0Gj+XL/gpqo=,tag:Rzhlj3zUMF8HikUbTRf5mQ==,type:comment]
  #ENC[AES256_GCM,data:MOGB+kCvJ+Ni3AoGxJW/vrKabGtT3/i1d1/i2Q5mI1xl15lCcals58h7wQ9hwfAFDz19SiOmGU95hMWPLJlyfzIlnKiDLK6lcGL5xR2e,iv:C72IF5cXydcCSyL2F5F14EcharYwUIh2/+i0oyck6dA=,tag:NOsXW5yKp6pModZJ4hnwEQ==,type:comment]
  CLAWDBOT_GATEWAY_TOKEN: ENC[AES256_GCM,data:YPl+zKxg9yAunZ/B7RqtidLwKRt6oWtySraXqn/rk72Nq+hKoYWM8mzIOkyE5iuA,iv:by2wKqNqKK/3nYDU/wIJlLZ4z5ej864ui9SpvTszedM=,tag:K5JxIuTpjmt4xCmmCFuMRQ==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c3pQRlNkWmJ0cVlrVDRi
        enJiQW1nZFFvT1hGMVRRWUlxcGJDZGZ2RldBCncwLzRJZDBxUEN5K0VLekFRcTNz
        SDg4aTZ5QjM0SFNnMGtVNDJZbUNPOXMKLS0tIFJ4ZGlzNDg1a0hTbXd1OTBsdUJx
        VmprblE2aldoZUMyWXo1RW44R2FnMUEKtELsm5jPdzKtaksQwenGoeVPMDo9DeB7
        jk/3fbEwpcWcsO4ROXEiAXDuV0DW6GPwyssGG3ndpV2vJBu35fO3SA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T21:10:08Z"
  mac: ENC[AES256_GCM,data:B4HQq5bpHKUPI7M/+yZQaoyIPSePC39VmlfqcdyjgkFjeC6GWQS+yoU6fxufnTzjkgBhZP5tKyGfBxnGNonmeUZSDFTrdOAN0uNNC4ZBlFIyZfLLVPVYdLbIu36D5NIjGoO20x/MMn/CFPtpQFahg4Me7J/Yh22m04gdJDqPO9Q=,iv:0p0lGXqoR6NmZ6ChxdbGOf9HZTJ4DoGZkjZ1ylYP87Y=,tag:LlZdVY6hpVHjVYJBkkeBFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
