---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/http-proxy
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./resourceclaimtemplate.yaml
