---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: qbittorrent-settings
    literals:
      - VUETORRENT_VERSION=v2.24.2
generatorOptions:
  disableNameSuffixHash: true
