apiVersion: v1
kind: Secret
metadata:
  name: bazarr-jellyfin-api
type: Opaque
stringData:
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:M0UGLLx39ytjddk1OOKkIwQ0kaEhWtf7Zqm///UkCpk=,iv:lrOHZSzWxpOE/kwH32aVwtDZ5VY9fxhRXV5YGEKtGw4=,tag:ixVGs4mkAO6apPwHiFNk0A==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQm9JSHhodHhJSVBoMTFa
        dHo1cE15akVCK3J0bU1rSG1QcTFNY1Bsc3lJCkxBK0dLRUlQQ0kzL1N5dXNoVkhZ
        RVlxUVdISHBKYndkRnZIbTZvVWdjaTAKLS0tIDR3bVl5bm80NGtYcityaytJeEZ2
        MlM1S1NjQWRFQS96c0FsWEtxQlhEb1UKWnqPH1kMUdZgUdvblE8Z5wvmBXfgvHi3
        iQ9tfTrje9iwDS6zqxCwG4Qlq9a7hoQ4HFdCdPMGTeG/6q4UBKRmOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T02:19:40Z"
  mac: ENC[AES256_GCM,data:zPkaYyfMvFm2H6np3ExD7cmHP2k/yWkPDlrwIfMUVgKDiWdK6iS/De58wy8z3cUdm0hMyfGi0ETp1RK10zsfdHt2W4b9A1MBZH2x+LQL4N1lq27cc1Ku+5xtAZbujqkplVn7DsJnlaqfqLRXxGs4r5omH8j4M8uFfiTkrz29p1A=,iv:3PaQ0SUc6RhF0OxGIkCs+Usmj4/7l3kUtkqVD2LU5d0=,tag:froMfBF7OU/0skaHUs+S2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
