---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: obsidian-livesync-config
    files:
      - custom.ini=./resources/custom.ini
generatorOptions:
  disableNameSuffixHash: true
