apiVersion: v1
kind: Secret
metadata:
  name: obsidian-livesync-admin-credentials
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:dCMcC6qFiTE=,iv:fwNdN78QczZbgHrS7EPYG5GnZHgGqLzS7dngpi05r4o=,tag:7iL0dTZUkr81/U0wj7rEAA==,type:str]
  password: ENC[AES256_GCM,data:qEapvgYfB8J0ZVd6Qjqo8hBq8qXr9iqlOh2pbUO5Mc7KywatVZEarZrkWXay1tpf,iv:hmdOIXQuJHyY827qr34f4WRj4vcrT6SVjkpnYDpwAKM=,tag:abXF39xse/QZ6bWBrUHspg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSG1DemZhb0k2clJjb2hw
        dGtEN0VDK2d5Z3ZSdVlVc25RZmZSR1ZWS3pzCnd3eHNxTlpuL0lWZ2lNRVJCbUFY
        TE51S1VxZERreExQTUp6b0F6MTlZaUEKLS0tIGdyWGlrMFg0aFBNKzZEWlIycEln
        NnhMaGErc0RlZGRYTVdEeElqQU9obHMKKMYQ7LBKTey9j7EFkhEVaPUrdm8LWles
        9E8UPbKm65xzJARVsbzejeiHUUXIS0sAYlWbS4ZyorxQbmHD9jwd3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:32:51Z"
  mac: ENC[AES256_GCM,data:bvfiaQTio1jmvcbPJM+wcT2dT30oJJkVWvJwjU5+RfLfAza/3o/oUxz+Ucq3PxY+hLEb0MGfJx+Pu6FUCrkvnL3fzqpGQAV8gPbzyklvTIwxPRg+zg3jkvjeGHLM17OKubEB94aV41Xbg9AKMl/qzD21BH4Ev3V1axPF+skE5Qs=,iv:J2ZTXhBOj6iZTPjTXIfl8x0sjkCMG/8zP4xjC1D2KGg=,tag:/wgf6+6DOJbayqAeVxrPaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: obsidian-livesync-cookie-secret
type: Opaque
stringData:
  secret: ENC[AES256_GCM,data:NonD1h9RPDu+lHPxYOSj57MXYonHSdizgG4yNRloUGJmsKFPFS4qFcUMijrxDeWc,iv:BbB8KN1KctASL4Bw2zx0aDzaa3T6W9EGZR5RzDNvANE=,tag:IoFCXfSM6GpIb1BG3FpIzw==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSG1DemZhb0k2clJjb2hw
        dGtEN0VDK2d5Z3ZSdVlVc25RZmZSR1ZWS3pzCnd3eHNxTlpuL0lWZ2lNRVJCbUFY
        TE51S1VxZERreExQTUp6b0F6MTlZaUEKLS0tIGdyWGlrMFg0aFBNKzZEWlIycEln
        NnhMaGErc0RlZGRYTVdEeElqQU9obHMKKMYQ7LBKTey9j7EFkhEVaPUrdm8LWles
        9E8UPbKm65xzJARVsbzejeiHUUXIS0sAYlWbS4ZyorxQbmHD9jwd3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:32:51Z"
  mac: ENC[AES256_GCM,data:bvfiaQTio1jmvcbPJM+wcT2dT30oJJkVWvJwjU5+RfLfAza/3o/oUxz+Ucq3PxY+hLEb0MGfJx+Pu6FUCrkvnL3fzqpGQAV8gPbzyklvTIwxPRg+zg3jkvjeGHLM17OKubEB94aV41Xbg9AKMl/qzD21BH4Ev3V1axPF+skE5Qs=,iv:J2ZTXhBOj6iZTPjTXIfl8x0sjkCMG/8zP4xjC1D2KGg=,tag:/wgf6+6DOJbayqAeVxrPaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
