apiVersion: v1
kind: Secret
metadata:
  name: obsidian-livesync-admin-credentials
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:dCMcC6qFiTE=,iv:fwNdN78QczZbgHrS7EPYG5GnZHgGqLzS7dngpi05r4o=,tag:7iL0dTZUkr81/U0wj7rEAA==,type:str]
  password: ENC[AES256_GCM,data:QgccmFSovys1ooZ8BW5RVon1UL2XRPJtqRGCmqyvX80O6RdlQRO9L7Cp2c+y6HGk,iv:5HGY4B59JrDWJwH9ZpFQxpAeuaQz9iZ2zdA253vnJ9k=,tag:/e437zhCipi7bPjSQQbHew==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSG1DemZhb0k2clJjb2hw
        dGtEN0VDK2d5Z3ZSdVlVc25RZmZSR1ZWS3pzCnd3eHNxTlpuL0lWZ2lNRVJCbUFY
        TE51S1VxZERreExQTUp6b0F6MTlZaUEKLS0tIGdyWGlrMFg0aFBNKzZEWlIycEln
        NnhMaGErc0RlZGRYTVdEeElqQU9obHMKKMYQ7LBKTey9j7EFkhEVaPUrdm8LWles
        9E8UPbKm65xzJARVsbzejeiHUUXIS0sAYlWbS4ZyorxQbmHD9jwd3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:59:28Z"
  mac: ENC[AES256_GCM,data:q+ZB7lIzdlqqstbBxZ899c7fu+J0BOzghfWLgNrWE3bDiWdtGf+S4O/feOq6PKx3wyit1NoQ++5S+WtjNUzGuhUxYttxbvBkiHqjimTzDvruz6ovGMCjAzxfTFAILNr6S4RRTve3CembAXju4GX4VHhEyytEzdvRK4cHXsjK15E=,iv:OVhg8u56YlcmoPXLoyA5sXsKP1ZibHFwWQBxP9bHB+A=,tag:gRLgfRnUxQjUZuXtkxFvZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: obsidian-livesync-cookie-secret
type: Opaque
stringData:
  secret: ENC[AES256_GCM,data:3u4zhDpozKm0KyzPyXAw75LLek0O0ygOqCnS6JkPZpZtc4EXfZy2Mn133XRtpd/JJXHuCh+yxeOaJuz7dFI0nQ==,iv:OwLlbi4MCp6X7O9J5keBcy1iNLg2GENAWbDELzeY4gs=,tag:ak+hT8S+tDZfAqxr5Q3mNA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSG1DemZhb0k2clJjb2hw
        dGtEN0VDK2d5Z3ZSdVlVc25RZmZSR1ZWS3pzCnd3eHNxTlpuL0lWZ2lNRVJCbUFY
        TE51S1VxZERreExQTUp6b0F6MTlZaUEKLS0tIGdyWGlrMFg0aFBNKzZEWlIycEln
        NnhMaGErc0RlZGRYTVdEeElqQU9obHMKKMYQ7LBKTey9j7EFkhEVaPUrdm8LWles
        9E8UPbKm65xzJARVsbzejeiHUUXIS0sAYlWbS4ZyorxQbmHD9jwd3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:59:28Z"
  mac: ENC[AES256_GCM,data:q+ZB7lIzdlqqstbBxZ899c7fu+J0BOzghfWLgNrWE3bDiWdtGf+S4O/feOq6PKx3wyit1NoQ++5S+WtjNUzGuhUxYttxbvBkiHqjimTzDvruz6ovGMCjAzxfTFAILNr6S4RRTve3CembAXju4GX4VHhEyytEzdvRK4cHXsjK15E=,iv:OVhg8u56YlcmoPXLoyA5sXsKP1ZibHFwWQBxP9bHB+A=,tag:gRLgfRnUxQjUZuXtkxFvZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
