apiVersion: v1
kind: Secret
metadata:
  name: obsidian-livesync-admin-credentials
type: Opaque
stringData:
  username: "obsidian"
  password: "4d93c21f1b5bfac9af8a9e651efce202a5199e3dfc6099f5c23b5ae7cc25ddcd"
---
apiVersion: v1
kind: Secret
metadata:
  name: obsidian-livesync-cookie-secret
type: Opaque
stringData:
  secret: "8d74253c7e09e9de03c27a9e3e8aab1ab654e00ae914fadf96f3458f39fabf07"
