apiVersion: v1
kind: Secret
metadata:
  name: radarr-exporter-secret
type: Opaque
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:JN3K1hIxN8HsyyoNW7Z7X2UR7umxhLYNXyRNGF1jusE=,iv:lJnX7ZAFq4nOPQJmZY8FHQ3k6QndQZ1KE21l5QPjMcE=,tag:XfQa8YhLTvrpr2PAXw9d9w==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eEkzL0lCdFJXQkUvS1NO
        dlZkSVA3dmVJbHZsYzFOOGFNajZrZzlNb2tzClRDWjJyTVg5ZExxNW9HWjVIVGp3
        cTNjMUVEdTM5QVk5STJkNG1weDJOaGsKLS0tIEgyclZoZ1pHcnVoYVJiSVRJcWRv
        S1o3bC9DcnQvN21QajJrY2xCbGlMUGcKMRhvQnL7U0IO47b2t2f/c/JT+3ULLxkw
        XtAy1/jawWbcZS5irXPjirQknt26h9Czm+L8dLipjMNHcMi+JrOAKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T23:31:15Z"
  mac: ENC[AES256_GCM,data:5PiH+pD3zo4R99mYffnuY1mfwRJGo6WDc2yR1QuIJvM1TRNTXIv8SxjDqnHsbOjCMfGla1C5yGFQ4obIUBr+jKbA4cDZwSFeWvIBuksgJhCIoer0LOMr0kWjW7L28NpCt/qMUN/a8tEIu/7AZnKa1oRjoRoHqjFp14ro4r/umSY=,iv:voBbEJo60Rkb68a/VBkiOreI51GJmBta1qasyopeMlA=,tag:4ifFrBhPb5S/7jTIR1issA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
