apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-exporter-secret
type: Opaque
stringData:
  SABNZBD_API_KEY: ENC[AES256_GCM,data:FARdpLkNwp+Eg4INCEo8C2LA49x3U7mVXGrrUaUyEd0=,iv:2SQ82qbImG5C+txRjR7YKmPj/1NyJIh7do/9QEWn55o=,tag:ryaCdgtkfVUmpFJNTv6/jw==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVTU5TUpPZXZHSUJURy8z
        S1pCL3BHY1pKd3NsaE9NVkhUcE14NldsMlVFCnpRZy9FaXJub2hObm1ZVmU3NzVj
        TldjSUN6ZW9KZ1M1ZWh5b3hpMlRrQ2MKLS0tIHRRWXJkc0RYNmY5UVFUV1lLWHdG
        aUpoUUJhY2lQT1AwcExwMUF5K3JCcEEKuYFbfgVxsXfUcZYOL8892OUXiWY61DNk
        wlE6a6y11DRgdKXhBX8VVmFCblHYCfrMzYOrO3zaLJpV4huGn3azEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T23:31:39Z"
  mac: ENC[AES256_GCM,data:2knMt3fYtKj9P29wZSM6nV3MaS7vYzTH793kQNpOVoXvLt1MUZOpPjvj1ArSSU+s6Ejq2TRoHJfJTFAixkKgxPDaDKGcrZFAgtz4/c4SvJ7MrjcnmMF08UVOmjUGNOShRjzMDdRBr1QAoAD+gWPDIlgZ4flgl3ZfKD02hBplgW4=,iv:yvBHkVtlqMOKsl1KTwLihwkNgiDzg2em5td6DDtyXgk=,tag:XU+ZOCMpw0y0qx0AOnRdsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
