apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret-key
type: Opaque
stringData:
  secret-key: ENC[AES256_GCM,data:qveDJKlLrCj7u32r/wb+w0wgkmCXlv0Ik2vXjV4HUOcbCPKFnCuJczgNE3/69+PI,iv:rcGWut+TA3Zql9lwtQetBE+Y82/2pqZOE7to1yU4z2M=,tag:QQP1iUxgKHXWN3HfhywgLA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RW40Q0NyNWdyOUY3aGww
        VmhuZ0JpdkRFMjNnck1yVytwR25sbWljcHhVCno3NHlTV2ZSaUVsWFladldhdWFI
        Q1c1KzB6eFd2U0RITTNlUHlRbU1Vd28KLS0tIHVnYjEyZ2NVRkJXWlhXMVc1OWl4
        QW4vaWNEeHhGeTlPbHZZUWNXejJLNlUK9m1G3LWY4QIKNZ4BVaOf8cAMl6KM50zx
        3KVMES1g7afbltR3yErIgHRRFeQ+QQEFN0nClHbGBHvAImLKfnkEUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T16:51:27Z"
  mac: ENC[AES256_GCM,data:xm1WKvboepPFn3RPBAkM/hiPklnhAwm/vNFIJtrrRG7rGBlp783CuB/1KXQrj9tx/07u13Jo/d7pC6OwLZubi3c2S5uHEgv5cqdAC9D2rPNiYbl2xKzopqS8VEfLDn1Cwt8yt35OKVQ0G2R/qTTv/qOr3XhBh8qAfqSe4xr6nw0=,iv:SXQK8akgANav8uoJ35Ozzdpt11Bq2HwXejGYnV1HbAw=,tag:d/rQj85E5FiiyRu8zqHIYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres-credentials
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:3oT0Cvkse7R/yywMBABysVMOopgdT53kDv/apYbZhwv7vs3OH4qBHqZfqgVxjH1l,iv:PjFsoUMjbIDX3mgq6G4n1Kwj7oxXWoRkehDriH68UnY=,tag:oIJKgNfkRTmj4KgpHKe+3g==,type:str]
  user-password: ENC[AES256_GCM,data:ewaLlJaaKRCmiJ0O1uwc5iRmk71ORYHykj5AVA7qVc5uf/Or8VCP4QATdhQg8qnO,iv:CnEvOXwVqU5KVDmvRhJdwMspF6Fl50eQN1bG2AYKaMs=,tag:2dcCRQTpRaD3W2Qu7m/J2w==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RW40Q0NyNWdyOUY3aGww
        VmhuZ0JpdkRFMjNnck1yVytwR25sbWljcHhVCno3NHlTV2ZSaUVsWFladldhdWFI
        Q1c1KzB6eFd2U0RITTNlUHlRbU1Vd28KLS0tIHVnYjEyZ2NVRkJXWlhXMVc1OWl4
        QW4vaWNEeHhGeTlPbHZZUWNXejJLNlUK9m1G3LWY4QIKNZ4BVaOf8cAMl6KM50zx
        3KVMES1g7afbltR3yErIgHRRFeQ+QQEFN0nClHbGBHvAImLKfnkEUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T16:51:27Z"
  mac: ENC[AES256_GCM,data:xm1WKvboepPFn3RPBAkM/hiPklnhAwm/vNFIJtrrRG7rGBlp783CuB/1KXQrj9tx/07u13Jo/d7pC6OwLZubi3c2S5uHEgv5cqdAC9D2rPNiYbl2xKzopqS8VEfLDn1Cwt8yt35OKVQ0G2R/qTTv/qOr3XhBh8qAfqSe4xr6nw0=,iv:SXQK8akgANav8uoJ35Ozzdpt11Bq2HwXejGYnV1HbAw=,tag:d/rQj85E5FiiyRu8zqHIYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
