apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BZ9o4P6S5Yo63fbSokSWgtsXT4AwQOvrPZTE3LeUEQI1bKQNSW927g==,iv:G+bFnpv3K7ou9BMStOgpigaCcumRCpE08yA4rT406uQ=,tag:hTPVrIPQyWCHX0OWg2+e0g==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cVJuUmxyYjM0WnI4Zktm
        b2ZCQnRqSlhmZnVobnVuaTYyTStHNTZ3Um5ZCkc2OGpqN2drNlpjYUdZMElLMTRm
        WjJlU1ZoVEdRWFZSL2dqM3ZHdDR0VU0KLS0tIEFabWEyRmsvYTJ4dU1qOHd0dU1l
        KzVsaEdCOGhhRGtVc1hQV0FEQmowTEEKkij7yVpJzAiS1W06t40xR5FbolfsLxo5
        f8NDhCFZ5mAwhOjgT9Vfv6iV2aSr9SOK2PHpc9s6a4OMZAPubueeUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T20:28:58Z"
  mac: ENC[AES256_GCM,data:tL0ka4/cM7BaZrliXXwEww0g3o3pmr8TjbSEN+26l1NN6R9BUEr99QHnJxPgrwnVn/kH5B7mckSO+hlBua50hMucVzCvs96Glc0gJ35l+pbBpJSi/gxmIGq0sYhr5olTk2loWG8UhQA4dWShe/d4YONWF/yPdycEqCbNyvwCodk=,iv:+MXc9ggzo1iTvUkRk40kffnlgSCEXjUUh1ENTTrJUII=,tag:hm9pqyKfbCQNMZKukbZOOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
