apiVersion: v1
kind: Secret
metadata:
  name: opengist-openid-secret
type: Opaque
stringData:
  openid-client-id: ENC[AES256_GCM,data:VY+u91Z6n8dy2OmD6Yi6/UuEun8nV7mZ/ZFTU63DVUg34xfFKQP7kQ==,iv:a3qKfMkd75n0swrHUlkyd/GDpHf5VXKBF/SjcqxfPPU=,tag:MadLIJ16YypclO922kS1PA==,type:str]
  openid-client-secret: ENC[AES256_GCM,data:r14UPlRHzwtmWw0Z6WtiRgPAU5abrx+l6CIlOYSAHTPdhkoCMPfvdcncvIqiGEq//Ij1mEJeOeI335jSLXmbbTt5qVB6BCdKb9BbEiKcpgcJMGOKVJF1BehJwjJsZ86wlv6sarQXiQpIsrcDLvZVyb3Cc3fbPp3KILjV4vtnYxY=,iv:6K7qk8WoN0uKAohYw4m05/myZTqHljLCpY3IZTIjkHA=,tag:92BkcwRiAQDeKas9xYXm+g==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOTlBV3pmS2svS3FRNFdC
        alg1RjdPeDY5eFFQK1JPTEg1L3lIZ05IRG1nCnQzZGJPN2Y3WjBWWVlFbU93ZFYz
        d0pUNHJmalVWMDJlVDVUSzJBOUl0TmcKLS0tIERaUWtFWjJ3RXBMdkRxL2FjdmdP
        OFdacDVXaHFPd0Q5a09DOXhtVEd2QlUKMfbpp+ipBOJSAyPoglCMHs/SKEDe/jeg
        tRc5gxW5oHmdxEgKMEHu0F5Ca0yO4fA8SN+XWsi8tcYG7m/xLoQrcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T01:35:53Z"
  mac: ENC[AES256_GCM,data:HJRJs7Tgz9BwQL9Lc+g+MtJ9PeOk0mGsKUXlUTymRjJrioNYbA15L1MEBMVir3bVmFa0V2AwkCWAOjSveub3s1aRFq0fuDbUV/gWAi4Zxxa8G1qKjq5xKr9PPJd3njdnuDHocFaAITt2x/YnFWsesgPtS+RBBg7MZlVH9J8AAGk=,iv:Tg6rq8p1wWb0Bltqn4gB1MI6pogMmvg1q8pklQHb3yQ=,tag:k/wfCUP0IaUkg+Mv/5RkzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
