apiVersion: v1
kind: Secret
metadata:
  name: opengist-openid-secret
type: Opaque
stringData:
  openid-client-id: ENC[AES256_GCM,data:AY+Nerhj/Es=,iv:cUbDgshnsAVAqf2z2UTC5GjcrcWIw1otyoNMvFDqcW0=,tag:hoxJLWOCuviIPCNRgpm2ZQ==,type:str]
  openid-client-secret: ENC[AES256_GCM,data:NIO4AACy6MM=,iv:QHRv4x1Eao94YU4OZcmCeuh7rGeibC8Q2en+PNHupLo=,tag:M+EwB55lymGNuvJlbrYZ4g==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOTlBV3pmS2svS3FRNFdC
        alg1RjdPeDY5eFFQK1JPTEg1L3lIZ05IRG1nCnQzZGJPN2Y3WjBWWVlFbU93ZFYz
        d0pUNHJmalVWMDJlVDVUSzJBOUl0TmcKLS0tIERaUWtFWjJ3RXBMdkRxL2FjdmdP
        OFdacDVXaHFPd0Q5a09DOXhtVEd2QlUKMfbpp+ipBOJSAyPoglCMHs/SKEDe/jeg
        tRc5gxW5oHmdxEgKMEHu0F5Ca0yO4fA8SN+XWsi8tcYG7m/xLoQrcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T18:32:47Z"
  mac: ENC[AES256_GCM,data:T/fJU+PdbeD5Jg3hpPOwj076lN8l1UrA2OKPO5CqSU+0ZGSh0rli8shjxuUhIOoI3xCcFClilmz+4FojciX8vBV75iFSePiRHGaPgVADkMwKt210E71GJsA1lg11qlQIHmCP+ZFhGaWm75dPy3eY0VgizXBYgJvKEBRjFRqk83g=,iv:XN3smu62o2wBipYmAwB6xXofOtyupnf3zHc/4yTwgF0=,tag:fDL6IkSHxPRj/WhesKuJPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
