apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:lQ1MC1c=,iv:dTUdFhaI64rwNhhtHv8CfiS4FQletjquMWVFbUMpwBU=,tag:daHxAq2Qk89YOSdNHXiI+Q==,type:str]
  password: ENC[AES256_GCM,data:aRVmwgiyfr68nEE4RLaEJcYE4PspNHBBACZEVQ==,iv:2SMQj9tEj4wapSTxWWdHAt7nt6eq0rFZN+csHoJrZ7o=,tag:eYAgYVgeKO7xcl9tzP1WKg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYzlOUFBwL1lIcnB0VU00
        K3hGT2ZXTWU1QU4rWjdlM1dNb2VraEZMYUNRCjVZOTBFSS9JOUVuU005ZmJReXpF
        TjdBMVN6YnpHazIyR3U1NEhJZlFPV0kKLS0tIFlJakRnVkFhWHFNOEtmMlJ2dTNQ
        Si9aZzBzUzJTbi9IcmxUOXBWNHFqdkUKO87az2fD2bSGQLB96DjIXMJoNUAuBiZy
        eWuuzVx4QR64Dol97NDfolp4R/8ndTlWLCPagSYD2FfHFY7r3MuVHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T15:34:03Z"
  mac: ENC[AES256_GCM,data:a59Ebex68JgvWp+Ku96a8Kn90J8p7WungRg3uvKlFfrOPtqGMQHQUGgjF+xUuH1nhHQSn15RyAjM5ye17rW/Mo/IPu5bjeUreMvTLYmgd3gKgp1mWEP3Xuygru3Z6UF2vPl2+REtthjtwGQVpvMh+E8FzUxtmxJW4ZkHRGgF/vU=,iv:KqQwIfHiUTqAB6DDTWwRHuEPc+/LpdgfWNQfvcAW5Lw=,tag:NX856CEPugk/4aE8HQqIFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-authentik-oauth-client-secret
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:x+4eXhOupb6PI7cl0LFrVIZ4AOoFtz2ohgh44mok3itSKnMV7FDPWg==,iv:btGwRGqyParir1kbf9G3/ksIhs3kkmHaS6+lLA87PY4=,tag:7jLmrRnSkzuEExenva3Pvw==,type:str]
  client-secret: ENC[AES256_GCM,data:tC2jmscEUrWDQseUkRjX7T2fTljQqfByaFsMmnRhGcYJGb2WuwVByXhJ9O6RIcwbuL/aakqWhA8zGVWc904IK/z4gHYGVQzIvxPZowbO50lkmclehTE17tqpzhJ25CuLir1mRPNuqhidXIPvcbxByYtY+RaP6BkFRWFXDvRbaJQ=,iv:3P6j8FqBkXqIH+IollOgXHPiC1Et4+atvl68rhy6KWE=,tag:dVC8h1Gek8eKxG9MXPL9NQ==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYzlOUFBwL1lIcnB0VU00
        K3hGT2ZXTWU1QU4rWjdlM1dNb2VraEZMYUNRCjVZOTBFSS9JOUVuU005ZmJReXpF
        TjdBMVN6YnpHazIyR3U1NEhJZlFPV0kKLS0tIFlJakRnVkFhWHFNOEtmMlJ2dTNQ
        Si9aZzBzUzJTbi9IcmxUOXBWNHFqdkUKO87az2fD2bSGQLB96DjIXMJoNUAuBiZy
        eWuuzVx4QR64Dol97NDfolp4R/8ndTlWLCPagSYD2FfHFY7r3MuVHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T15:34:03Z"
  mac: ENC[AES256_GCM,data:a59Ebex68JgvWp+Ku96a8Kn90J8p7WungRg3uvKlFfrOPtqGMQHQUGgjF+xUuH1nhHQSn15RyAjM5ye17rW/Mo/IPu5bjeUreMvTLYmgd3gKgp1mWEP3Xuygru3Z6UF2vPl2+REtthjtwGQVpvMh+E8FzUxtmxJW4ZkHRGgF/vU=,iv:KqQwIfHiUTqAB6DDTWwRHuEPc+/LpdgfWNQfvcAW5Lw=,tag:NX856CEPugk/4aE8HQqIFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
