---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: telegram-bot-api
spec:
  chartRef:
    kind: OCIRepository
    name: telegram-bot-api
  interval: 1h
  values:
    controllers:
      telegram-bot-api:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: aiogram/telegram-bot-api
              tag: "9.3"
            env:
              - name: TZ
                value: Europe/Moscow
              - name: TELEGRAM_API_ID
                valueFrom:
                  secretKeyRef:
                    name: telegram-bot-api-secret
                    key: TELEGRAM_API_ID
              - name: TELEGRAM_API_HASH
                valueFrom:
                  secretKeyRef:
                    name: telegram-bot-api-secret
                    key: TELEGRAM_API_HASH
              - name: TELEGRAM_LOCAL
                value: "true"
              - name: TELEGRAM_VERBOSITY
                value: "1"
            ports:
              - name: http
                containerPort: 8081
                protocol: TCP
            probes:
              readiness: &tba-probe
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  failureThreshold: 3
              liveness: *tba-probe
    service:
      app:
        controller: telegram-bot-api
        ports:
          http:
            port: 8081
    persistence:
      downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: downloads
        globalMounts:
          - path: /home/app/downloaded
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /var/lib/telegram-bot-api
