apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-api-secret
type: Opaque
stringData:
  TELEGRAM_API_ID: ENC[AES256_GCM,data:gHBeifwlX/g=,iv:LTiO9tpFZs+CD8YHsee7KckkUpPp7FrvQqRIvnK8Ivc=,tag:JLHBWUTGTLi80Hr3hfvkQw==,type:str]
  TELEGRAM_API_HASH: ENC[AES256_GCM,data:clKBu3tRMqlNmOQSRxk0/vryVT1ZQqoerKV/yvJu4+A=,iv:3TxOnHzwTR5svJaAH0aUYQYtq9WK+T2Wl3G+tc5/HD0=,tag:HZjHhKUwR4SXQ1vhYwyAvg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLejNRcGFOdjNnWFp3WmNG
        MWNJZENQYXhYbFZCRDFiWjVlQU05dEp3Sm1VCkNXTStxUEhKQVVjK3U1cHpnbHBs
        MEZZUG5vZlhYdDFyRGNwdzBINnRtYzgKLS0tIERJRHZkMkpVVEY0T0NHWTNiZU5K
        VTZ4ZGRjR3Y5L0o2L3RvS2N1ZmluV00Kp+BrWzs387NU5MPdSrqWEvG0egkgcwje
        NSSgVQp+9UVnaDP/JkfkGy1/Dmqzv6Q06oTY4y7pAsxZs2mUyLVdeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T01:43:05Z"
  mac: ENC[AES256_GCM,data:jLEEhA7AAm1E4YrmwJMx3W+jhoZzsEHeJ73La5JG90vmm7m8AOLv6Ez+7ZH1BN/OKlGfuoCaon8KXTsj43HhBy6N/9ncenOCO63VWywxXFaJA04hr+X9hNFpLv2WPIGWptJeUkcEiIW0E2VAa2pZxaiaK8LBYaPhYnpWAdVGywM=,iv:Ip0oIgp+46hsco+WvYv5lnt+NOGT4S45k3JEHENYVFg=,tag:LJEdgAGYScghWfOJ874hTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
