apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SahxWMHxgxF7zkNLdUs=,iv:FoU3UDs4WTqBPSbSXgD1BmX3vYyZsadWPSYaIXYaLrs=,tag:d5l504G7GsxIVfZUl1HBaQ==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2gwSlZTN3Jpb3JZSnVR
        YlVXRUdPdENaeFZSbGNyOGpRZWFZaDN2a0E4Cng4WW94UkdwTFoxVXhIRnJWKzFi
        a01nVUZBcURoZTZzSDhKaks0b2NUUjQKLS0tIGdDN1A4UWJ6aUZtcDhNd2x5MnND
        cmtOaEVyVmNuWERzWG5WVkFpaE1yUFkKk7fQaF7dUlAmG0nSHhitm1DeM+sgPrq3
        YLlWvqjuTd0x9SOt8cbVKDUHvvKvnNsrkrCDDM/0JDr979dRKxNjvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T20:28:58Z"
  mac: ENC[AES256_GCM,data:ljgPm3VeQC/ImdFJZoKQckiLBdT5gf8Z5ceJ78O2v8ZKWTnkfiO68bhOF2fHDz2EC28Gqcp39xCwH9Ytg21RVN5RIridBw7hqjRh8XBJUdmvwZRidHuKpi/3ZYyyITz8ncmr0wMdBG+buU9WyvxFIWOwcjyugdV5rVWD8dYfFNg=,iv:WHPruerX+n42OKGPIAsDkr9yVbmGJ2/St7CGaZK62d4=,tag:/1f8g1WVol3UOPspjZQg6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
