apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SahxWMHxgxF7zkNLdUs=,iv:FoU3UDs4WTqBPSbSXgD1BmX3vYyZsadWPSYaIXYaLrs=,tag:d5l504G7GsxIVfZUl1HBaQ==,type:str]
  SECRET_PUBLIC_IP: ENC[AES256_GCM,data:KoyJ2N4+/bDtbDpdHA==,iv:cRoiFyVS1jnNFhhnPLlDhLYMwoQrcF1kkDGDlCC4Thg=,tag:GiuiVfVzdVC+p4GspLo1UA==,type:str]
  SECRET_TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:7k+IO0/OSZt8,iv:i3pUbO9VwJdfuav5dKUSF+ms+gqluQa+j5P8zknWVIk=,tag:s7wgm2mKRQkWcX3G/GSKqw==,type:str]
  SECRET_DEADMAN_WORKER_URL: ENC[AES256_GCM,data:92WOAD+RwaqxboPEqeoMwPCm3B31HwWWrwmD5M/rtn8EVAUy7G5fcKX7zcBP,iv:jGqj+yF0/6+PD1nf/6BX3QE4Io3KM3i5KfUv5C+Bm+M=,tag:u9kQsIt+UQih86qtT4xS5A==,type:str]
  SECRET_HTTP_PROXY_URL: ENC[AES256_GCM,data:ztyS3chT6IiPbJnC/yxBm4gJqWp8rzEoWfbz+kPy27XWnWtmFjGq8SmGEiA=,iv:WB9tV9qcX3hhj87dHAARbn5G0ROtn6YRim5Zx6K9Dgg=,tag:WCZB29Cs5vL/EBXFW3ey6g==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2gwSlZTN3Jpb3JZSnVR
        YlVXRUdPdENaeFZSbGNyOGpRZWFZaDN2a0E4Cng4WW94UkdwTFoxVXhIRnJWKzFi
        a01nVUZBcURoZTZzSDhKaks0b2NUUjQKLS0tIGdDN1A4UWJ6aUZtcDhNd2x5MnND
        cmtOaEVyVmNuWERzWG5WVkFpaE1yUFkKk7fQaF7dUlAmG0nSHhitm1DeM+sgPrq3
        YLlWvqjuTd0x9SOt8cbVKDUHvvKvnNsrkrCDDM/0JDr979dRKxNjvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T19:52:37Z"
  mac: ENC[AES256_GCM,data:Z2o/JXuLYL6yeWrsAJgFWNT11iwJHbGtmeST8bU9IAZNSxdwX2RM0yCe4/KBg7lCChlZDPqJ9U3hj+wL36F1145wqRONtRyCLmSBNIUELJn/e9Q4jmNX7Ij6ZRSZSZ/SDZdJPjsd5xEKL/00FBJHNDtQ0RizZJY9resd31Gy3vg=,iv:o2o6ccE68Pxplvs7b1isYwQHYcj2VJMIpJwS0Sn2by4=,tag:REaRT7DNwiVg6r56FUrtjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
