apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SahxWMHxgxF7zkNLdUs=,iv:FoU3UDs4WTqBPSbSXgD1BmX3vYyZsadWPSYaIXYaLrs=,tag:d5l504G7GsxIVfZUl1HBaQ==,type:str]
  SECRET_PUBLIC_IP: ENC[AES256_GCM,data:KoyJ2N4+/bDtbDpdHA==,iv:cRoiFyVS1jnNFhhnPLlDhLYMwoQrcF1kkDGDlCC4Thg=,tag:GiuiVfVzdVC+p4GspLo1UA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2gwSlZTN3Jpb3JZSnVR
        YlVXRUdPdENaeFZSbGNyOGpRZWFZaDN2a0E4Cng4WW94UkdwTFoxVXhIRnJWKzFi
        a01nVUZBcURoZTZzSDhKaks0b2NUUjQKLS0tIGdDN1A4UWJ6aUZtcDhNd2x5MnND
        cmtOaEVyVmNuWERzWG5WVkFpaE1yUFkKk7fQaF7dUlAmG0nSHhitm1DeM+sgPrq3
        YLlWvqjuTd0x9SOt8cbVKDUHvvKvnNsrkrCDDM/0JDr979dRKxNjvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T17:23:56Z"
  mac: ENC[AES256_GCM,data:tKxXfbd42Q9hdUsE9o9TWDTsFs7iKspxjrxhkK/NTiZ71JjutGb2cACuKidtb1dXI/BNfnwD9IZRaekIZlcTK0dwHNXtP+iu8y8pY71ws2Z/HIi4xBogtzPg9qPRj73eIKLMRRW2OZLtY1jT1wUS1E5k6GJdm4axHO7HEuRLPNg=,iv:dyZ9ZYLSNUvUuYxvtFlAP754WIBoHOnu6uiPgnncIns=,tag:orCQY2pv0UtN/DIlziDWNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
