apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SahxWMHxgxF7zkNLdUs=,iv:FoU3UDs4WTqBPSbSXgD1BmX3vYyZsadWPSYaIXYaLrs=,tag:d5l504G7GsxIVfZUl1HBaQ==,type:str]
  SECRET_PUBLIC_IP: ENC[AES256_GCM,data:KoyJ2N4+/bDtbDpdHA==,iv:cRoiFyVS1jnNFhhnPLlDhLYMwoQrcF1kkDGDlCC4Thg=,tag:GiuiVfVzdVC+p4GspLo1UA==,type:str]
  SECRET_TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:7k+IO0/OSZt8,iv:i3pUbO9VwJdfuav5dKUSF+ms+gqluQa+j5P8zknWVIk=,tag:s7wgm2mKRQkWcX3G/GSKqw==,type:str]
  SECRET_DEADMAN_WORKER_URL: ENC[AES256_GCM,data:92WOAD+RwaqxboPEqeoMwPCm3B31HwWWrwmD5M/rtn8EVAUy7G5fcKX7zcBP,iv:jGqj+yF0/6+PD1nf/6BX3QE4Io3KM3i5KfUv5C+Bm+M=,tag:u9kQsIt+UQih86qtT4xS5A==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d2gwSlZTN3Jpb3JZSnVR
        YlVXRUdPdENaeFZSbGNyOGpRZWFZaDN2a0E4Cng4WW94UkdwTFoxVXhIRnJWKzFi
        a01nVUZBcURoZTZzSDhKaks0b2NUUjQKLS0tIGdDN1A4UWJ6aUZtcDhNd2x5MnND
        cmtOaEVyVmNuWERzWG5WVkFpaE1yUFkKk7fQaF7dUlAmG0nSHhitm1DeM+sgPrq3
        YLlWvqjuTd0x9SOt8cbVKDUHvvKvnNsrkrCDDM/0JDr979dRKxNjvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T01:56:44Z"
  mac: ENC[AES256_GCM,data:Kbjugj1e0TAWHFcQxs2xAhvuTD4sUu41eGqTnx9vXDjfwozeXzC1sI6heKQRVQFDKv/OIvCmUnJJo+B82zD6gMXGZVLsAlhaM4oTFt062AAYfU53xM6cJkxFzG7yxJ83AgJ72njgOWl4lJJ+ESBJ9l9bMO62efc5nZ9UzsG1Df0=,iv:usu/Dfmu2fTZvxNME9ohwd8eby5wI43kd6CHF3cG9ro=,tag:P9XGjflcDVGEi4mIP8elQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
