---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: glance-config
    files:
      - glance.yml=./resources/glance.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: glance-pages-config
    files:
      - ./resources/pages/home.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: glance-widgets-config
    files:
      - ./resources/widgets/qbittorrent.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
generatorOptions:
  disableNameSuffixHash: true
