---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/vpn-sidecar
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: glance-config
    files:
      - glance.yml=./resources/glance.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: glance-pages-config
    files:
      - ./resources/pages/home.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: glance-widgets-config
    files:
      - ./resources/widgets/qbittorrent.yml
      - ./resources/widgets/arr-releases-radarr.yml
      - ./resources/widgets/arr-releases-sonarr.yml
      - ./resources/widgets/arr-releases-lidarr.yml
      - ./resources/widgets/jellyfin-stats.yml
      - ./resources/widgets/astronomy-picture-of-the-day.yml
      - ./resources/widgets/speedtest-tracker.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
generatorOptions:
  disableNameSuffixHash: true
