---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/vpn-sidecar
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: glance-config
    files:
      - glance.yml=./resources/glance.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: glance-pages-config
    files:
      - ./resources/pages/home.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: glance-widgets-config
    files:
      - ./resources/widgets/qbittorrent.yml
      - ./resources/widgets/arr-releases-radarr.yml
      - ./resources/widgets/arr-releases-sonarr.yml
      - ./resources/widgets/arr-releases-lidarr.yml
      - ./resources/widgets/jellyfin-stats.yml
      - ./resources/widgets/astronomy-picture-of-the-day.yml
      - ./resources/widgets/myspeed.yml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  # Icons from selfh.st/icons (CC-BY-4.0)
  # https://github.com/selfhst/icons
  - name: glance-icons
    files:
      - ./icons/adguard-home-light.svg
      - ./icons/authentik-light.svg
      - ./icons/drunkenslug.png
      - ./icons/easynews.png
      - ./icons/grafana-light.svg
      - ./icons/jellyfin-light.svg
      - ./icons/lidarr-light.svg
      - ./icons/opengist-light.svg
      - ./icons/overseerr-light.svg
      - ./icons/prowlarr-light.svg
      - ./icons/qbittorrent-light.svg
      - ./icons/radarr-light.svg
      - ./icons/rutracker.png
      - ./icons/sabnzbd-light.svg
      - ./icons/slskd-light.svg
      - ./icons/sonarr-light.svg
      - ./icons/stash-light.svg
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
generatorOptions:
  disableNameSuffixHash: true
