apiVersion: v1
kind: Secret
metadata:
  name: glance-secrets
type: Opaque
stringData:
  GLANCE_WEATHER_LOCATION: ENC[AES256_GCM,data:XujIhpRcdwb25d9bW7T+DBJ0edQ3VV8i,iv:HJZ9oMkNf7QpeiIht2X/H85tnTlaEJnFKQda6uRe80Q=,tag:sGnjHDBsht+/6WDBxL3jNA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUXhoeTJuVnRKYktiOVUr
        dzMvNkdLYjI1U2FXM2ZXZXZ4aU5JeWpBNUE0CkZRTnRDT2Z0ZDBqeWMwTnJQVk5I
        NHZNZGNpSVhNVi9BUVNWUmN1ZDMrelkKLS0tIEhaZmVINmhkZUQrcEY4UGMzbTZM
        WTdwZnpyY3hraXVkN3Fad1FOdXpiSzAK3D3SAZG2SUVlFzdceJA7UnYgKPF1sAiU
        5scSOHTm1WgPRuc422D0ghmWIr9HvEUZNvvZ10emVbnUl36WibBO4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T17:33:52Z"
  mac: ENC[AES256_GCM,data:f7MMwl0pns+kNOX5l6+L5L65ExTgmLGEkA1GzsXLSusnWdXf4e+eVkEw7j4gicCgrlbjN7eikGIIvZarAFNIfxsDHGG7SMZiX7JrinIfH3EI2YNEcHU9cDmJC4PLe3cGqAYEPNonNAUMyLkN62RbVNtoljSETjuz8OTHdS8Fx4k=,iv:PR180TD4cU/6ExA47ji1VT/5anzUEGEif883Lbupyxc=,tag:JzmiS2aD20+c+qsaJy40Hg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
