apiVersion: v1
kind: Secret
metadata:
  name: glance-secrets
type: Opaque
stringData:
  GLANCE_WEATHER_LOCATION: ENC[AES256_GCM,data:XujIhpRcdwb25d9bW7T+DBJ0edQ3VV8i,iv:HJZ9oMkNf7QpeiIht2X/H85tnTlaEJnFKQda6uRe80Q=,tag:sGnjHDBsht+/6WDBxL3jNA==,type:str]
  RADARR_KEY: ENC[AES256_GCM,data:+MXLvRZCICpPn4NKOPdX0kuz+HaEfYpexXjLS2TJzPs=,iv:TEwzkbd+OJeD3a2fx/U7k39nuD2ZGr4Z1wqxdf7QAxY=,tag:tWcfMnY0RoAtCw03l/qmCA==,type:str]
  SONARR_KEY: ENC[AES256_GCM,data:H8sg/h+BThTarSWD8viP/lkQvx7qZD0O8ySU0zQE7J4=,iv:7EwyM70zQy4YKm/E9XcTTFFOXvvKPO3ogkngngEAA1Y=,tag:7u/cH2SKM/hJwIFC7FxJHg==,type:str]
  LIDARR_KEY: ENC[AES256_GCM,data:lF5hixKpdPpFVaIrXcQl99SRCRrMSlX/YjGCHHV2Zd8=,iv:dQrATYh8JFq6jSlsrFSJvYCdvujpvSlMAmf3MKynaB4=,tag:RmbsCQ9v07X+ebQmSfE11A==,type:str]
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:R1z7IIP5VbeplVmSle2yurBa/ES2reXr9ZCjvfAU/wM=,iv:9iexU9Lmbo2QvxPEn5Of7CRElBCrFxSslVFlFDtuQcg=,tag:EXUBTqG46ycLYQC+h5361g==,type:str]
  NEXTDNS_PROFILE_ID: ENC[AES256_GCM,data:4Wmfauxz,iv:TQ1EdBVx+pCLHiwCguGGO1TT1iOSnl/4zQC9zCj33kA=,tag:YznDcGW8zCsDs0sbLEukLA==,type:str]
  NEXTDNS_API_KEY: ENC[AES256_GCM,data:DiOIDg4GfFzOk2DKZwaZL1uNJq/pmfq82Bt3ZD4IP6MwsyiBiaWJtQ==,iv:eb/exU6aW/Z+f7LCz+zrW9uxSiNbJ88F0kOAeKSfFI4=,tag:Okh2S+S6JIwqxtzD4OwQXw==,type:str]
  NASA_API_KEY: ENC[AES256_GCM,data:KCPmoPwq2KtVpdfpZ7R4MSeWN0YUbjNw/Vcz9vRiZxBK1uEnKjgGWA==,iv:voy8lLqTbT+anp8HERdd+His6IwMzZ2Q4CnFuNXZex4=,tag:rQD3OuMXmqnVGZwkRdgIKA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUXhoeTJuVnRKYktiOVUr
        dzMvNkdLYjI1U2FXM2ZXZXZ4aU5JeWpBNUE0CkZRTnRDT2Z0ZDBqeWMwTnJQVk5I
        NHZNZGNpSVhNVi9BUVNWUmN1ZDMrelkKLS0tIEhaZmVINmhkZUQrcEY4UGMzbTZM
        WTdwZnpyY3hraXVkN3Fad1FOdXpiSzAK3D3SAZG2SUVlFzdceJA7UnYgKPF1sAiU
        5scSOHTm1WgPRuc422D0ghmWIr9HvEUZNvvZ10emVbnUl36WibBO4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T16:44:48Z"
  mac: ENC[AES256_GCM,data:ilzyknT2++cjxO2ubb+7aVHkUXshpZR1FqrFxmy/N1LXrJCaNKqUf5Lc+P1mGJBwZHiaqBCK3v/NVTIadzfmx9oE3+CP5n5fRpP/3Oiwwy+73B9nol5BhhOYGCsar5ijIW9p8pTo++vXPit8TxMy59KXZBpUAU2TZhz4SdvwCw4=,iv:5vToUvprq02rQR9yKkLnRrXQjepDdhM3ULQwLR8fiDQ=,tag:FQGy94nrIf5psMFJ6YdBCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
