apiVersion: v1
kind: Secret
metadata:
  name: glance-secrets
type: Opaque
stringData:
  GLANCE_WEATHER_LOCATION: ENC[AES256_GCM,data:XujIhpRcdwb25d9bW7T+DBJ0edQ3VV8i,iv:HJZ9oMkNf7QpeiIht2X/H85tnTlaEJnFKQda6uRe80Q=,tag:sGnjHDBsht+/6WDBxL3jNA==,type:str]
  RADARR_KEY: ENC[AES256_GCM,data:+MXLvRZCICpPn4NKOPdX0kuz+HaEfYpexXjLS2TJzPs=,iv:TEwzkbd+OJeD3a2fx/U7k39nuD2ZGr4Z1wqxdf7QAxY=,tag:tWcfMnY0RoAtCw03l/qmCA==,type:str]
  SONARR_KEY: ENC[AES256_GCM,data:H8sg/h+BThTarSWD8viP/lkQvx7qZD0O8ySU0zQE7J4=,iv:7EwyM70zQy4YKm/E9XcTTFFOXvvKPO3ogkngngEAA1Y=,tag:7u/cH2SKM/hJwIFC7FxJHg==,type:str]
  LIDARR_KEY: ENC[AES256_GCM,data:lF5hixKpdPpFVaIrXcQl99SRCRrMSlX/YjGCHHV2Zd8=,iv:dQrATYh8JFq6jSlsrFSJvYCdvujpvSlMAmf3MKynaB4=,tag:RmbsCQ9v07X+ebQmSfE11A==,type:str]
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:R1z7IIP5VbeplVmSle2yurBa/ES2reXr9ZCjvfAU/wM=,iv:9iexU9Lmbo2QvxPEn5Of7CRElBCrFxSslVFlFDtuQcg=,tag:EXUBTqG46ycLYQC+h5361g==,type:str]
  NASA_API_KEY: ENC[AES256_GCM,data:KCPmoPwq2KtVpdfpZ7R4MSeWN0YUbjNw/Vcz9vRiZxBK1uEnKjgGWA==,iv:voy8lLqTbT+anp8HERdd+His6IwMzZ2Q4CnFuNXZex4=,tag:rQD3OuMXmqnVGZwkRdgIKA==,type:str]
  SPEEDTEST_TRACKER_API_TOKEN: ENC[AES256_GCM,data:7MIwDUKpujg5zBmhdNJU4k5l4EE4OqQJUo8ajlrgII6sU2uYynz9sC4iDzNo3ZXw,iv:oa9tT5hzAlvg13V1euPo8ftvb6O058jeGu6EXgJZYDg=,tag:bZ2xI8RjWZOMpiljoAll6A==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUXhoeTJuVnRKYktiOVUr
        dzMvNkdLYjI1U2FXM2ZXZXZ4aU5JeWpBNUE0CkZRTnRDT2Z0ZDBqeWMwTnJQVk5I
        NHZNZGNpSVhNVi9BUVNWUmN1ZDMrelkKLS0tIEhaZmVINmhkZUQrcEY4UGMzbTZM
        WTdwZnpyY3hraXVkN3Fad1FOdXpiSzAK3D3SAZG2SUVlFzdceJA7UnYgKPF1sAiU
        5scSOHTm1WgPRuc422D0ghmWIr9HvEUZNvvZ10emVbnUl36WibBO4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:38:11Z"
  mac: ENC[AES256_GCM,data:uEnSpMlOwfsCvqAKSP717L06kFS9DYnz78/NTqimsreCl73mtCk2V1a9Bk1thdMouVqY+/1zxH6kJb0wZMNdgXPnH8tmrImbTVXMHPDc5vxYhll/6AtQeCVKYmzjgE3h44Eut+ivgGrsFjrc41Nq9ylZA7nULsGVVDIgkEJm5lQ=,iv:/ULu7R/JizS+P6DTlJdIiOa5875ZGWG5cdOM28Sazo0=,tag:ZxkbznvLMZJq7WxeSXSEbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
