---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-instance-rules
  namespace: flux-system
spec:
  groups:
    - name: flux-instance.rules
      labels:
        namespace: flux-system
        app: flux-instance
      rules:
        - alert: FluxInstanceAbsent
          expr: |-
            absent(flux_instance_info{exported_namespace="flux-system", name="flux"})
          for: 5m
          annotations:
            summary: >-
              Flux instance metric is missing
          labels:
            severity: critical

        - alert: FluxInstanceNotReady
          expr: |-
            flux_instance_info{exported_namespace="flux-system", name="flux", ready!="True"}
          for: 5m
          annotations:
            summary: >-
              Flux instance {{ $labels.name }} is not ready
          labels:
            severity: critical

        - alert: KustomizationNotReady
          expr: |-
            flux_resource_info{kind="Kustomization", ready="False", suspended="False"}
          for: 10m
          annotations:
            summary: >-
              Kustomization {{ $labels.exported_namespace }}/{{ $labels.name }} is failing
          labels:
            severity: warning

        - alert: KustomizationSuspendedTooLong
          expr: |-
            flux_resource_info{kind="Kustomization", ready="Unknown", suspended="False"}
          for: 15m
          annotations:
            summary: >-
              Kustomization {{ $labels.exported_namespace }}/{{ $labels.name }} reconciliation is suspended
          labels:
            severity: info

        - alert: HelmReleaseNotReady
          expr: |-
            flux_resource_info{kind="HelmRelease", ready="False", suspended="False"}
          for: 10m
          annotations:
            summary: >-
              HelmRelease {{ $labels.exported_namespace }}/{{ $labels.name }} is failing
          labels:
            severity: warning

        - alert: HelmReleaseSuspendedTooLong
          expr: |-
            flux_resource_info{kind="HelmRelease", ready="Unknown", suspended="False"}
          for: 15m
          annotations:
            summary: >-
              HelmRelease {{ $labels.exported_namespace }}/{{ $labels.name }} reconciliation is suspended
          labels:
            severity: info
