apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Z0Vsi29tnC9U2UmniBIVyQVMlCkscc0Lh/61TeiGzr0=,iv:2Sv1Qc94KshQG5zW6bD4Hzk/AvCPMAgAXXOrpo/8OZM=,tag:LXzFlrE1wRS2NnP6SuNu+w==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Sk91YzVFY2JPSks3dkFH
        enlQQ0p0V29PTUkycjFkZ2w4MnQ2LzlJRGtZCm1nVll2Y3IxQkgxS3p1VzZEelhZ
        SU4vZThFRE9ScFhLUHZHekV2ZEkvNWcKLS0tICt2cGd6MVROMlZaZTgzQWNMSU82
        N0V3anQ3and6Qlc1aVVjTzI0UlNZVUEKZV7Cu5fc7+zK9+baD2/eaClvtbWcTqK0
        2HOjzOmt6I7sVtwOKhYfmMYP2lBHn1RKA/XFtDuV2WdhK+uNsg0YQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T20:28:58Z"
  mac: ENC[AES256_GCM,data:aMrDSP3rFxfklT42V1a5p92Ksvj9yQttYNzfrisKhr3EOL+U4pXj63ysSfMy+CaNl54NtqdZovHKUI5MkBLzfT/JyrCBRItMGKut9h4T5MHUexZLx6hHuDWKx3/VH8tWsJ2mirzt6xMBQRmwI7e9ybFr4yGP5SAh/vB3vyA0j3I=,iv:PCqnfLa1DS95ySdECYTc0CcOFnvumXlWtJrb1uh00jI=,tag:BFIq+su4OlyO4I59sn7lNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
