---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./loki/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./k8s-monitoring/ks.yaml
  # NOTE: Remove grafana after verifying kube-prometheus-stack works
  # - ./grafana/ks.yaml
