---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./helmrepository-grafana.yaml
  - ./loki/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./k8s-monitoring/ks.yaml
  - ./smartctl-exporter/ks.yaml
