---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
spec:
  chartRef:
    kind: OCIRepository
    name: mongodb
  interval: 1h
  values:
    controllers:
      mongodb:
        annotations:
          reloader.stakater.com/auto: "true"
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: data
              size: 5Gi
              storageClass: openebs-hostpath
              accessMode: ReadWriteOnce
              globalMounts:
                - path: /data/db
        containers:
          app:
            image:
              repository: mongo
              tag: "8"
            env:
              - name: TZ
                value: Europe/Moscow
            ports:
              - name: mongo
                containerPort: 27017
                protocol: TCP
            probes:
              readiness: &mongo-probe
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 27017
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  failureThreshold: 3
              liveness: *mongo-probe
    service:
      app:
        controller: mongodb
        ports:
          mongo:
            port: 27017
