---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/vpn-sidecar
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: stash-renamer-config
    files:
      - config.py=./resources/plugins/renamerOnUpdate/config.py
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
generatorOptions:
  disableNameSuffixHash: true
