apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-exporter-secret
type: Opaque
stringData:
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:vcMucp88I+mSeIBGEkA4uuI9Txr0ensbkLw0gcEriDw=,iv:iROx4rcPjIcvEaJipAbIOLrZNYXzf4GKVYUjvNKeGhs=,tag:Z3+PyM24q3oHyKBVoHmDfw==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcFdzcTBUUXNQdkx6YUxM
        WWJJMGxHM3J0c1VuTkVDT01qUlV5R2hwL2s0Ck9DTFVWOE5TZmN0TjBOMGpYSFVs
        aXYzSFFpZnROMEdmSW4rajhPOHRqMEUKLS0tIENxd2ZSNC82YnVWS2FKWllFWXg2
        TCt2TzVtczl1LzNCdFF5a1FiL1dFSGcKJL+6iZc7Q2m+jCqRLk3fwNnCdIYuDTOk
        MR2yfvSx46yo/f6izDEqpvjjiD0WTdH9xFeyL1YtluOlb+3benWx5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T23:31:43Z"
  mac: ENC[AES256_GCM,data:6gKDmX3tnWmKGFF5vr8DAzIf6ErNLwUm7VyOu5OYs8c61LJ+CrxQp6B+VMUDvbbK4S844JoVM8J9MtJ6rAxUXUen4eQFOwt+6Q5PrCkrCkMNgc/gcHMTWZe4ioGYAuwXODvtHdx9w1xamjKlJaijWn0b0AcGwXAicKu+2TzNQGM=,iv:LOBTm/l6CBamQgBPA5A9QkX0fDhYYx+O5wXLyefOJOM=,tag:O0PsCxo6qASdlp1CZIPFMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
