---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soularr
spec:
  chartRef:
    kind: OCIRepository
    name: soularr
  interval: 1h
  values:
    controllers:
      soularr:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: mrusse08/soularr
              tag: latest@sha256:c1cfc6425c1cc141f5f99744611eeb1af32c85258df5e2a4974d7dbf6db76840
            env:
              SCRIPT_INTERVAL: "3600"
              LIDARR_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: lidarr-api-key
                    key: api-key
              SLSKD_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: slskd-api-key-soularr
                    key: api-key
              TZ: Europe/Moscow
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 100Mi
        globalMounts:
          - path: /data
      config-file:
        enabled: true
        type: configMap
        name: soularr-config
        globalMounts:
          - path: /data/config.ini
            subPath: config.ini
      soulseek-downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media-data
        globalMounts:
          - path: /soulseek/downloaded
            subPath: soulseek/downloaded
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp
