---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: soularr-config
    files:
      - config.ini=./resources/config.ini
generatorOptions:
  disableNameSuffixHash: true
