apiVersion: v1
kind: Secret
metadata:
  name: lidarr-api-key
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:YrWV3UiIFd/g9hwAtjtw8boutvWjXBRdh88r7RB/lwk=,iv:2wKFAOvr5vE8D881M1gUXXU8QGALpAw3JBlQvGYjVng=,tag:o1GCyTppJohOWXu8OSRv7A==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NElQZjZGNVVCN1d1eEZT
        NWs3V3g4VGw1TzkvYlE1RWhnTU9aWVF1K2tZCndacmdUZ2Frb1oyTDRIdEw3aC9R
        cTJMRGpENG11TDBBNm1sWmJDalp5UlkKLS0tIDdTQWQyRW4za1JxRkRZWTFhcnBY
        UUc2NTFaYlFzWWhLaXk4OUxlY0xBYjQKDCUYa2J46DBHIJGRjli5JjJzd6fTMqcE
        d42KnqTFYK5wBO89v7dk/nkgVBctfO0jLZwT58c6Ffqkh3zt+Ac94A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:42:56Z"
  mac: ENC[AES256_GCM,data:grCunX3mIpMJtjtY9fJfgOc7TnWEiVY4rmVfuRxeIB+/IGzJy0acTXQJ0GwdbAcgjF+b25LUMzBHGysa7VkaBToEILB5quGwQXKlw1CIbDDgaDco1RzMs9r/PI3azGMO3IkVhl5j70My75I4/1J9fd5V+6yf0UzAHOLqWiicCFw=,iv:S5/4HJ4dawtoodMnjPvwMSgomwcZWgqkyBtBJTBpVzk=,tag:EgXIo8b8IlJkXcxibKapDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
