apiVersion: v1
kind: Secret
metadata:
  name: bazarr-exporter-secret
type: Opaque
stringData:
  BAZARR_API_KEY: ENC[AES256_GCM,data:jDAY+giSP5vMb6sIUbmNNf2T+ZxBmOfnovUz5KDo9Ic=,iv:uN+XPI5qanltrxlaTbG4px1lgZTst7TtUb7bBuz9hkQ=,tag:7+s+nHdHZBlHz77c4Qlq3g==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbWhQRFBaaXI2aFhhVENw
        c3FwMElHUE80bm5rV3lueGZwYUVFNU1wYkY4ClVyd3BBcHhHekRESkZEd1Yxc2lQ
        R2hlUDk2TkxLc3lpMW1UWFVMYUk0eWcKLS0tIGRzVGtZMXNzajl5cFFtbDR4RkRF
        bjdIR0lsdWEreFlmOHRSRGxvOWJVb1kKmcVTz/hUcWu+4YC4qWSvivNUd/VCpuzR
        n5oRXvn3FRHtR044j1bbxOANFXXMNIOGJ7wDCtwmDb2G6hv4VR1tow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T23:31:35Z"
  mac: ENC[AES256_GCM,data:IppTSn2P6xpCtZ76IEw+xILwzjoSkIh3OQUiHry2k0ulhuBvfT0CjtVftGBhTlcPcIQPU2sFvSMiQzkfkhEqmGE0IPn2W4DhlFu35EeE00ODNEEIH5J0zRckCLjOsLbP/vVW7F0dhjCMwln2yrogYr5GK3dI3UrJ1EtlYCgzn3k=,iv:HuC5gTyCEmdh9kBhgUrmjoZ1bYjt3jXZX2BSzgxDTKM=,tag:Ke9Cpo8ZmYFaCIZOjhjUeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
