---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./media-data-pvc.yaml
  - ./echo/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyfin-xxx/ks.yaml
  - ./stash/ks.yaml
  - ./lidarr/ks.yaml
  - ./backrest/ks.yaml
