---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./media-data-pvc.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qbit-manage/ks.yaml
  - ./pinchflat/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyfin-xxx/ks.yaml
  - ./seerr/ks.yaml
  - ./stash/ks.yaml
  - ./lidarr/ks.yaml
  - ./slskd/ks.yaml
  - ./soularr/ks.yaml
  - ./obsidian-livesync/ks.yaml
  - ./opengist/ks.yaml
  - ./backrest/ks.yaml
  - ./glance/ks.yaml
  - ./speedtest-tracker/ks.yaml
