---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: pinchflat-yt-dlp-configs
    files:
      - base-config.txt=./resources/yt-dlp-configs/base-config.txt
  - name: pinchflat-user-scripts
    files:
      - lifecycle=./resources/user-scripts/lifecycle
generatorOptions:
  disableNameSuffixHash: true
