apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:xa75M7CWCP5gUrq5PqoH6nhZFKR1QJF25jufFWBcxqAN9GFvag4Iw012/r+vqS5pa0qq04TAH9Mxj+blXVbQJrDOIAmz2kSVQBsXqmqkpTSAhrFVHLtkbh5ma47CNSbTGjWiB4/pEQBG0kgv5UPBb1nJ1CgZ75GY8XOayJyqlC9PMb6ngWFHRklJ+sj4TlPk9wHVDBN/2y+l3KlEzNDBQk/OOVlj7/QT7UgtIqXhnG6sYvB1,iv:IqTwx5peZ/cviPsgakn7b1HA4trMgHQ9kEeaav3z+Xg=,tag:iM1FsJVo16WF010bvJDf+g==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNmhNN0Q2NHlyYXltZWVu
        TFVXOTBrS1FSNXdiZVFHNWhhL3RONDR5ZERJCmEwalU1TXBPUmw4NFFaQXJpVVQ5
        Vkp0cEhMWVJZVVVkMlc5OWFGMnprSlUKLS0tIEVocEtOZ045dStnT0RPMkhLbGlY
        V1h2WUZwTUpYcWZ1NS9FUmN4ZmQ1RXcKAPxo7KOeaolXBlgdRX9TzqWsHLAGBup6
        4UfU6SoxTB+Ino/t/V3PnOR/o1NArUJ+fT5un2ezc/s37O+K4VkHIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T20:28:58Z"
  mac: ENC[AES256_GCM,data:DWYs7hN788kd1d2B2BYoV4UP4c2fg4cjS5GuS5r2Yyskmjsf9qOV3TfXD4aXNoXy8JDkoDv2ENq9D8hG/P3iD5uZ/vhg3bIzriwSZaShA57Ii9Ma9pNCreAKpPFKSYafKSu1/SAGd0AoZfrzL27FdQT/s2BGCpXD3cU+9A4RvwA=,iv:G39EPzs+LXsYkIKWi+4AldAKTCO3nxfj4rjU3kFNIrs=,tag:/eqBgdzdYXpS/XZC8urJ1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
