---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pot-provider
spec:
  chartRef:
    kind: OCIRepository
    name: pot-provider
  interval: 1h
  values:
    controllers:
      pot-provider:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: brainicism/bgutil-ytdlp-pot-provider
              tag: 1.2.2
            ports:
              - name: pot
                containerPort: 4416
                protocol: TCP
            probes:
              readiness: &pot-probe
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 4416
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  failureThreshold: 3
              liveness: *pot-probe
    service:
      app:
        controller: pot-provider
        ports:
          pot:
            port: 4416
