apiVersion: v1
kind: Secret
metadata:
  name: speedtest-tracker
type: Opaque
stringData:
  APP_KEY: ENC[AES256_GCM,data:5eIWXPf30gmds300ymVCuxY/HeAY5XgH7SJevj2QmjtlzxTTeA6ne0WB2Bv/Tofv8gjD,iv:TjaqKv86nYBe5/nTz+i2rYUAd/ndN8e96dJkYMiMH8k=,tag:yfwQmcMgDkRUMkaoURpS6w==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eUE1YmliSmp5Q2hLK2tD
        WXlPUnk1ZGpRcU9ZMGExMk5mZEczY3hXUFRjCkRmRVp5MWN6WERVenhIMjZMd2tB
        MTJnNW5ubGRFM2JRa3JFSE1XcEZWK0EKLS0tIDVJRjJaZStTUXZrUnRoUWUvdU56
        VitKNE5TQUJ6VTVNNi83OWdxVzdnZkUKcW7dkX/lKdN3lcxLgvdk28vFTdmRivTc
        rJC6G1FYhzgw9qfBNstRX9SYTTxFs4WQrwRmr713vkUTizibc1C0oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T17:18:20Z"
  mac: ENC[AES256_GCM,data:gTzZn/rr1aqKGweZInaDe5lUwurw4mLDz5ztsbcHxiDKFfKlLZjLIkqjC5ublS1qLRMB9zCW7G0F7skDlXElqZXamCwrhf7l0kBYdanP6DnE6hycYA77IXXP12WA9EPyW82r642hkjWghUqD84xtx/5NC3OaWqW2+mr3xnWEE8w=,iv:JfoqdFjuLnw48h+56t35PA0c6ebIc5CLUB1QNolvX3A=,tag:Jul5KZwShln9Hd+4x7fHKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
