apiVersion: v1
kind: Secret
metadata:
  name: speedtest-tracker
type: Opaque
stringData:
  APP_KEY: ENC[AES256_GCM,data:9zxKvDdc6w0mQ9NzPylpEZO7ySwSX49J0bix4Y5vVrq+JuW56XZwy9BtxPYPSx7s,iv:9cRQg2rL1n3penQ2v1bcVMUnWR4yKlf8zIRfAfskCSY=,tag:tN94psjafyul9T+vpFqrrQ==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eUE1YmliSmp5Q2hLK2tD
        WXlPUnk1ZGpRcU9ZMGExMk5mZEczY3hXUFRjCkRmRVp5MWN6WERVenhIMjZMd2tB
        MTJnNW5ubGRFM2JRa3JFSE1XcEZWK0EKLS0tIDVJRjJaZStTUXZrUnRoUWUvdU56
        VitKNE5TQUJ6VTVNNi83OWdxVzdnZkUKcW7dkX/lKdN3lcxLgvdk28vFTdmRivTc
        rJC6G1FYhzgw9qfBNstRX9SYTTxFs4WQrwRmr713vkUTizibc1C0oA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T20:54:31Z"
  mac: ENC[AES256_GCM,data:KvXbzxOoLG8jl8FI2/eC1kx+pG0pgDeRpchXEuMw7oliU1G7ADhydDPm9zdXv3WU6u9H2HYZuJjKo5lu4XYmzSbfUDNrfX/zCNCm8P5C349kQDwMXgKUlcKZ2ZCLbP02t5l5DjEJN6LgxWqFva3OPjyt6PeZl+axO2gMJFZvYJ4=,iv:ACt/istKb9F67qhR1wpYbn+ry0r+UGsVr2uL0tUVPmY=,tag:U9RfkgolGwgr8cL2abEMYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
