---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: media-cleanup-script
    files:
      - cleanup.py=./resources/cleanup.py
  - name: media-cleanup-config
    files:
      - config.toml=./resources/config.toml
generatorOptions:
  disableNameSuffixHash: true
