apiVersion: v1
kind: Secret
metadata:
  name: media-cleanup-jellyfin-api
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:cbwzb4wY4/FzRdbru7LYG/DHK1GjSrFMZ/evcU41cZY=,iv:8yPpifGmi60CqPkH0VXZT7Il3nPHp5ny6tM5FKIgN/o=,tag:G7HExZyINNAe0GbbNUN8tA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObDRqRnhESGlpSHNlSGZz
        RERQUlA1T3FFS1ErajhsZnQ1UUtNTnpubzI4CkN5czBibTUrbExWbnhPTDNuSmM3
        SHhCbHlSM0wvc0ZuaHpCZnZsUTU2NE0KLS0tIGxTNkdnRlFhNVlLZmVxdXNFdno4
        b1lvUzA4VnRNMFpSU1dicEgyOXhGY0kKO8Q6b6m6Kwww7mncrosBFYk1676TEsb3
        MtokbHTb4hVbQKbQM52zYTuzTvmUKsfqoyjlSfwFNL9FQfts/JQdyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T04:26:49Z"
  mac: ENC[AES256_GCM,data:9HB5uBiIbGBKW1VN0PAI5jU4GjwXMgBO2KL7tlQioiFMjwDZSN4FYGwbkyDZDWFvOUZRUf6qESjKHSZ9KRKixkxRcbeJjW+nyusrGgcMs+wI5mT2Ygg9o8Y/sBWTJoz+AXE4D+3jAE7l6Nv00z4PMEMiqkeZuo6SyOFNGbm8lt4=,iv:BrNWOVdBf2l42Tc62/O1jBO50WXYPsuAwGbaOiXkU48=,tag:ocC96WqlHyfONkjlIlDQQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
