apiVersion: v1
kind: Secret
metadata:
  name: sonarr-exporter-secret
type: Opaque
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:RC9tPA8lHGr8hf76DDaSdcDuHOHLccAFEiHRx9N1omk=,iv:wL/6WtJP2UYRwwgDg7CSJEoSo9FsaFbdNEM9LCBi4wQ=,tag:PoVhT0ELUS2fehjk4xoSrQ==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R2owL0Y5VHkrbVI2T2ox
        SlNkeUJ6b2pHTHllV1hMZTg3eWg0NkpDMUdvCis4bndaTVI2K3ZwOC9hZ0s3QU1q
        dWZFc3ovTUZFaVF3RWFIZlRsTlduc0EKLS0tIEs2dTFuYlVTSThhbkc2bElVdUM2
        dnBHKzRXNEN2cmJGbndFWG8zZUJzRkEKwAxgtSykUks5GwMvwnjQbLyqb3IjWriY
        tnGk7JZQ9aW0uBV+6mAY59apA4QRxt5xTVNUBJWAKEuzf6gReWgWig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T23:31:21Z"
  mac: ENC[AES256_GCM,data:oVh1aFmqpSZhNg4riEWbPAqK8VqSuapj+KcbjficD3RA2c5KtJagw6xepTMNZpAe72+S1wea0vcXJtcdyU9KStbMD/vc4ZpHfdypOp50h8JIb15H2EatdUXgib5BJAJqMXO97bbwCewd61Ok7gD0gC2g+Q3N/sBtj7pXIpAv1uA=,iv:g//N7yZM7WsFRguhsRu6yhy4KWKSFVpSok3yAsf250g=,tag:ueZ8W0P5ASztzJo3SRHi4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
