# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json#/definitions/page
- name: Homelab
  width: wide
  hide-desktop-navigation: true
  center-vertically: true
  columns:
    - size: small
      widgets:
        - type: weather
          location: ${GLANCE_WEATHER_LOCATION}
          units: metric
        - $include: ../widgets/astronomy-picture-of-the-day.yml
    - size: full
      widgets:
        - type: monitor
          title: Media
          cache: 1m
          sites:
            - title: Jellyfin
              url: https://jellyfin.${SECRET_DOMAIN}
              check-url: http://jellyfin.default.svc.cluster.local:8096
              same-tab: true
              icon: sh:jellyfin-light
            - title: Jellyfin XXX
              url: https://xxx.${SECRET_DOMAIN}
              check-url: http://jellyfin-xxx.default.svc.cluster.local:8096
              same-tab: true
              icon: sh:jellyfin-light
            - title: Seerr
              url: https://requests.${SECRET_DOMAIN}
              check-url: http://seerr.default.svc.cluster.local:5055
              same-tab: true
              icon: sh:overseerr-light
            - title: Radarr
              url: https://radarr.${SECRET_DOMAIN}
              check-url: http://radarr.default.svc.cluster.local:7878
              same-tab: true
              icon: sh:radarr-light
            - title: Sonarr
              url: https://sonarr.${SECRET_DOMAIN}
              check-url: http://sonarr.default.svc.cluster.local:8989
              same-tab: true
              icon: sh:sonarr-light
            - title: Lidarr
              url: https://lidarr.${SECRET_DOMAIN}
              check-url: http://lidarr.default.svc.cluster.local:8686
              same-tab: true
              icon: sh:lidarr-light
            - title: Prowlarr
              url: https://prowlarr.${SECRET_DOMAIN}
              check-url: http://prowlarr.default.svc.cluster.local:9696
              same-tab: true
              icon: sh:prowlarr-light
            - title: Stash
              url: https://stash.${SECRET_DOMAIN}
              check-url: http://stash.default.svc.cluster.local:9999
              same-tab: true
              icon: sh:stash-light
        - type: monitor
          title: Downloaders
          cache: 1m
          sites:
            - title: qBittorrent
              url: https://qbittorrent.${SECRET_DOMAIN}
              check-url: http://qbittorrent.default.svc.cluster.local:8080
              same-tab: true
              icon: sh:qbittorrent-light
            - title: SABnzbd
              url: https://sabnzbd.${SECRET_DOMAIN}
              check-url: http://sabnzbd.default.svc.cluster.local:8080
              same-tab: true
              icon: sh:sabnzbd-light
            - title: Slskd
              url: https://slskd.${SECRET_DOMAIN}
              check-url: http://slskd.default.svc.cluster.local:5030
              same-tab: true
              icon: sh:slskd-light
        - type: monitor
          title: Utils
          cache: 1m
          sites:
            - title: OpenGist
              url: https://gist.${SECRET_DOMAIN}
              check-url: http://opengist.default.svc.cluster.local:6157
              same-tab: true
              icon: sh:opengist-light
        - $include: ../widgets/qbittorrent.yml
        - $include: ../widgets/jellyfin-stats.yml
    - size: small
      widgets:
        - type: monitor
          title: Infra & Tools
          cache: 1m
          sites:
            - title: AdGuard Home
              url: https://adguard.${SECRET_DOMAIN}
              check-url: http://adguard-home.network.svc.cluster.local:3000
              same-tab: true
              icon: sh:adguard-home-light
            - title: Authentik
              url: https://authentik.${SECRET_DOMAIN}
              check-url: http://authentik-server.authentik.svc.cluster.local:80
              same-tab: true
              icon: sh:authentik-light
            - title: Grafana
              url: https://grafana.${SECRET_DOMAIN}
              check-url: http://grafana.monitoring.svc.cluster.local:80
              same-tab: true
              icon: sh:grafana-light
        - type: dns-stats
          service: adguard
          url: http://adguard-home.network.svc.cluster.local:3000
          title-url: https://adguard.${SECRET_DOMAIN}
        - type: server-stats
          servers:
            - type: local
              name: homeserver
              hide-swap: true
              hide-mountpoints-by-default: true
              mountpoints:
                "/":
                  name: host
                  hide: false
                "/data":
                  name: media
                  hide: false
