# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json#/definitions/page
- name: Homelab
  width: wide
  hide-desktop-navigation: true
  center-vertically: true
  columns:
    - size: small
      widgets:
        - type: weather
          location: ${GLANCE_WEATHER_LOCATION}
          units: metric
        - type: bookmarks
          title: Bookmarks
          groups:
            - links:
                - title: RuTracker
                  url: https://rutracker.org/forum/tracker.php?f=100,101,1213,1235,124,1247,140,1457,1460,1493,1543,1576,1577,166,1670,181,185,187,1900,194,1940,1950,208,209,2090,2091,2092,2093,2097,2109,212,2198,2199,2200,2201,2220,2221,2258,2339,2343,2365,2459,252,2540,271,272,312,313,352,4,484,498,505,511,514,521,539,549,572,7,709,718,775,815,816,822,84,877,905,921,93,930,934
                  icon: /assets/rutracker.png
                  same-tab: true
                - title: DrunkenSlug
                  url: https://drunkenslug.com/
                  icon: /assets/drunkenslug.png
                  same-tab: true
                - title: Easynews
                  url: https://members.easynews.com/3.0/index//
                  icon: /assets/easynews.png
                  same-tab: true
        - $include: ../widgets/astronomy-picture-of-the-day.yml
    - size: full
      widgets:
        - type: monitor
          title: Media
          cache: 1m
          sites:
            - title: Jellyfin
              url: https://jellyfin.${SECRET_DOMAIN}
              check-url: http://jellyfin.default.svc.cluster.local:8096/health
              same-tab: true
              icon: /assets/jellyfin-light.svg
            - title: Jellyfin XXX
              url: https://xxx.${SECRET_DOMAIN}
              check-url: http://jellyfin-xxx.default.svc.cluster.local:8096/health
              same-tab: true
              icon: /assets/jellyfin-light.svg
            - title: Seerr
              url: https://requests.${SECRET_DOMAIN}
              check-url: http://seerr.default.svc.cluster.local:5055/api/v1/status
              same-tab: true
              icon: /assets/overseerr-light.svg
            - title: Radarr
              url: https://radarr.${SECRET_DOMAIN}
              check-url: http://radarr.default.svc.cluster.local:7878/ping
              same-tab: true
              icon: /assets/radarr-light.svg
            - title: Sonarr
              url: https://sonarr.${SECRET_DOMAIN}
              check-url: http://sonarr.default.svc.cluster.local:8989/ping
              same-tab: true
              icon: /assets/sonarr-light.svg
            - title: Lidarr
              url: https://lidarr.${SECRET_DOMAIN}
              check-url: http://lidarr.default.svc.cluster.local:8686/ping
              same-tab: true
              icon: /assets/lidarr-light.svg
            - title: Prowlarr
              url: https://prowlarr.${SECRET_DOMAIN}
              check-url: http://prowlarr.default.svc.cluster.local:9696/ping
              same-tab: true
              icon: /assets/prowlarr-light.svg
            - title: Stash
              url: https://stash.${SECRET_DOMAIN}
              check-url: http://stash.default.svc.cluster.local:9999/healthz
              same-tab: true
              icon: /assets/stash-light.svg
        - type: monitor
          title: Downloaders
          cache: 1m
          sites:
            - title: qBittorrent
              url: https://qbittorrent.${SECRET_DOMAIN}
              check-url: http://qbittorrent.default.svc.cluster.local:8080/api/v2/app/version
              same-tab: true
              icon: /assets/qbittorrent-light.svg
            - title: SABnzbd
              url: https://sabnzbd.${SECRET_DOMAIN}
              check-url: http://sabnzbd.default.svc.cluster.local:8080/sabnzbd/
              same-tab: true
              icon: /assets/sabnzbd-light.svg
            - title: Slskd
              url: https://slskd.${SECRET_DOMAIN}
              check-url: http://slskd.default.svc.cluster.local:5030/health
              same-tab: true
              icon: /assets/slskd-light.svg
        - type: monitor
          title: Utils
          cache: 1m
          sites:
            - title: OpenGist
              url: https://gist.${SECRET_DOMAIN}
              check-url: http://opengist.default.svc.cluster.local:6157/healthcheck
              same-tab: true
              icon: /assets/opengist-light.svg
        - $include: ../widgets/qbittorrent.yml
        - $include: ../widgets/jellyfin-stats.yml
    - size: small
      widgets:
        - type: monitor
          title: Infra & Tools
          cache: 1m
          sites:
            - title: AdGuard Home
              url: https://adguard.${SECRET_DOMAIN}
              check-url: http://adguard-home.network.svc.cluster.local:3000/control/status
              same-tab: true
              icon: /assets/adguard-home-light.svg
            - title: Authentik
              url: https://authentik.${SECRET_DOMAIN}
              check-url: http://authentik-server.authentik.svc.cluster.local:80/-/health/live/
              same-tab: true
              icon: /assets/authentik-light.svg
            - title: Grafana
              url: https://grafana.${SECRET_DOMAIN}
              check-url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80/api/health
              same-tab: true
              icon: /assets/grafana-light.svg
        - type: dns-stats
          service: adguard
          url: http://adguard-home.network.svc.cluster.local:3000
          title-url: https://adguard.${SECRET_DOMAIN}
        - type: server-stats
          servers:
            - type: local
              name: homeserver
              hide-swap: true
              hide-mountpoints-by-default: true
              mountpoints:
                "/":
                  name: host
                  hide: false
                "/data":
                  name: media
                  hide: false
