apiVersion: v1
kind: Secret
metadata:
  name: wireguard-nl-conf
type: Opaque
stringData:
  wg0.conf: ENC[AES256_GCM,data:2B8yl0jrZDeeTc2r1QGSb2yUunkUgB5HJx8yVNNUzll64+FaIXibDCmP3X4CWFcbbMd61UHD0q0ihOleg3cey4Ays1Of/iE/FXZ4n0wwzkF46Xl9hfGZvYg+XJ+FsKSsT07CMQLeQhurNaerE0osiKRgU0ADNG/p8QCoXXs8NtSCvT+Z/SEbXQ9Nx6c30GQqMu92Z/hT65klbd8nN7PNNPY5tFwY1e5ZcLsik+K3sin9J6T5xGlH/usKTKdsV7xTVJgClfrs6DyQv6SZ4YP0tWVoyzS0tYXtGEpC3F5Q7l7dL3qYfkwJahZepWEijUdBf8PDGuZ5W+4DGcUVLryNZXzBlZdwZfG9kqWrs+QTJjGBrMTnfAd+uw9faOEN3mLpYjnwYYDjHtDEqzhEPHEIZ739sSC5cM3hJzjH1ETdieyWEwZY9u2/zzF7OV3DNoYPaRnqoNISP6o9RmmrrqbmpbFVhDpYdLZgbS27Qth0au98iEPE6uMpLBFmo2QWT3CTXvZrfIbVSbIjc/WOiwnPoxgBqDvFYlRGZUWzaLMHnrM9BKgLlh4pAZYlyhl7K6By2knT4KwyqMjiLmdNgZM4Sv4vMBDcN43rBYjkA6eB1g8WsE6jP8UQNfxoRxLSR+w6d95CAX0jhrSjI+TWc8Y/QNw2NF/DKjFcmr46g1CtKZ9+JJx+i7sTeiDzPKKRcBqvKrvfwyoCnViZ+ipUqxDAFJr6lc4oJcj++hhIhO0xf26X36yoSgOUIVVLeS2NAWX1frEoGYqvHmMz99X6equ31/IcMti6FLxxvtaOW5FuST8JfnUsdcZlfw2+qnU+0EoEnl2maalhMSD+ZeOMzMw27yyUDtjJGyuUWfcF4hRQ/Wro0dSco5yhThQlWObaKh3A8PHFypRjnOIn32x+1s1UjbdAnhaePoA1iBVpz/KKdZd7NurzqfMYJHaTeAXHf9kLla2GROVA94IuX79xjf6ac1HxkJjkYyIqns3F7bJ0j9CxDfqAv6dckfTXy4Rab69FcbaBGX7ruB94x0qIsAlRJ9UZ03IHL/4vRnvzE1ZkgnD7VTMAul5aX+5enygV0YCgxmtTynTQvLZddPicCUybk9xjDcbQiC2i/ESYCQAvYPDy8ZSlyEDuiMQ6zRVSt4MagvpQKwwJ9qX39RYwZAaldxYK/31nQ8aICEgXTeLajYdFu9SQpvVsOZuskxni6hIzvDcGTBIpf90JsSGxHT3eP7XRxuEO3C8XsQJM/Knmvp33MaHkwlGg6OlIxUOg9TiBywFGW/YsXdiXlp5b9/wostggd8Js5eX1nz7SDtXAEAzVv+mVmV6nj5wBMzwR8hl5Hg53jCTeCz3wRra+vLB1dreT1i7pY1zlYy5aKu6gT/COrUzvPrQvAAlygwqD/+1pZxPKVDVkEMGTBWpt19A1Y6FS0mMK6qDhL7yBaCHDY5ouRoIMH1Ud4gKIZMJilx3DYRRpKFdG2K7TEJ2Ccg3KRqoiXrNVnbEyuREXCuPQp6QHglpwgr19smEndy4vuauDRFbE4MyutzceUlaY10SN0Kup39MBRf7w0ELwBpoWMWde2ZMKCObiwlycRi9I5ONFh9Czs0bqaAPTYiz9FMxt/ddNkuQw1kzfRtQe3WsxxXA7XTrOBc8z+xibrRwAx8rMrZXw5DlvJmNfiw==,iv:i7kjm4rEmpeytstBlco9PfZ5L7Ate8VHbqkiGadABb4=,tag:AIIecQYT+Fx3X1hGjG99ow==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaTZVUVJEeE5NZFQ5UU1R
        Nk1iL2NPQitlaytSQlozaU1RQSsrSGpTRmw0ClFaODhEYmZmUUJHU3VNbFJBQWZk
        djVqV2tPK2NHVk5YK1VzMDl1MWllc0UKLS0tIGNlSVdPaU83emZPRUpHRUVJLzBw
        R3I3aERXNVN3QnlwY3NsWGdHanZ2SFUKwoK71B0PFxWRpLymaT1KE5WKuDbZOXf4
        pE2uVcURfXsexSJGXvi/OM6w+I5MybNeYXuzMSABozUgvRJs42Am5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T16:32:42Z"
  mac: ENC[AES256_GCM,data:dyHlkgLbjqs+aGqb+R1wY1C5wTnIFRDDIidkV02Bl4xsQ31ONaTios3/ZNaEhhmBX26oYuXr6e+9WfSRWdA6zev5FeHHgnXm/9Bv4F/RrZ+KlR/md0KEj17GcXLThWeSlu4qLXn5YOj32NptsMFZlx637cfAQt+A+nd5vmB3sVQ=,iv:YxXeElMhQLcfrFHVtlkk3FZPM9zZdl9qtsMSfCORFbo=,tag:wdIh0losTUdiRZ412HCb1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
