---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bot
spec:
  interval: 1h
  path: ./kubernetes/apps/ytdl/bot/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ytdl
  wait: false

