apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:WM3fxxsuJR75QU5JUEk0efhhKMz78TKPETu80ww14lpk3UYlDrnrkQ==,iv:vp71eMrcz5LHePXEFiGN+1t5Il+cUXQYifG1iZmBfow=,tag:iAd/i43ERVR3ce/BDHId9w==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UWcycW1HeUhyMW54SVRN
        SlJ6ZUdnNG9lQUlyTGEwYXhaSitSbkFMS1dBCkQ2QUJ3eWdBclkzQUFGVmJmUjhm
        YnRlQ09UNUdIUG5oc0w3UnU4T1hxb2MKLS0tIDdyOWRTdXBFVFVFcnJHcWR6TEdC
        N0o2OEIwS0hJVnVXU09rWEZ1Ymx5WXcK+ZWQ7iSX50JBIErbDuxgdHiyEIrcmVeA
        TaVJvwXokK745+WxSKfW+R5eMG/7VZVlKm+QJfAhg0edOlJqezzHOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T20:28:58Z"
  mac: ENC[AES256_GCM,data:1/HrKz0XLMViPPpputYLG8WjXZtC904cdRQxGpgnAu963YIdxDXxo5hiN7ZxfM35wfEopSQmTDJoUtm+XpcQdEv4vCGvS0TqIqm917Sf/QyatmTenJ/Vlo0Pn97DjEf+l03oD1iLUtSZBxUDlqPYfs+6+2+aWE5PjHDFgefUln0=,iv:NfvxCzjkt0LenGdNOAIMJPKlR42DZjr1UfW8HW77i6k=,tag:hERoJWfvsVO8aJn0SSGz+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
