---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/vpn-sidecar
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: radarr-scripts
    files:
      - jellyfin-notify.sh=./resources/jellyfin-notify.sh
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: radarr-jellyfin-config
    literals:
      - JELLYFIN_URL=http://jellyfin.default.svc.cluster.local:8096
      - JELLYFIN_LIBRARY_ID=f137a2dd21bbc1b99aa5c0f6bf02a805
      - JELLYFIN_REFRESH_PEOPLE_TASK_ID=866456ed0d44e15468124ce33d85961e
      - JELLYFIN_INTRO_SKIPPER_TASK_ID=eed9a58097ab2f196265820308ec2e1c
      - JELLYFIN_MEDIA_SEGMENT_SCAN_TASK_ID=f861734dd71b37f9482b52a820e39013
      - JELLYFIN_PATH_FROM=/data/library
      - JELLYFIN_PATH_TO=/library
generatorOptions:
  disableNameSuffixHash: true
