apiVersion: v1
kind: Secret
metadata:
  name: radarr-jellyfin-api
type: Opaque
stringData:
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:2/uI//e5QL22ozl1I6vk+tWuflInkrdl6Rf9K7hhgak=,iv:LwdzjZshqzlOnajQqhfBmaSGNZSlkVX7hSJ7JS9I9zM=,tag:yECREdTr64ODmb4siHOtDg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRzVORmxOTE13T0JpT2tP
        WkhCNHRlSkM1dEN1c1I4ZnRMa0RTZ085K25nCmNsQkNVN2xSb1VObGRiandwT1d1
        RlR5NEpwWnMxeUdJRGRmNVhIeVREaGcKLS0tIC9Ea3ZmODNITTNWTXd4dUZFblVF
        RStkUjErUmxhQ0VVTFZxb0MzSFdHWGsKpGFai3lv/y1zQBxhfd0DeC3EtVuEOFPn
        VUa9y3DMURw6xbS57S3r4T5lAkTfaylLD71u8nvvUgZpHxMFvwUTdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T22:01:08Z"
  mac: ENC[AES256_GCM,data:0hV+EITcnf2tUaE3hathSBO08YhAVA42nWX3tupYB6CsIDzp1pMu+/T96F3qfkv2aKGhmt6jfDloWc2Qtm+y61cLBJ7gR76TzhNG/7swmUMisexEvoF16b0e2vUtyat0zi71u14U3CG8zX2hZyk7ro79xpmNDXx/5QxK3xFyiLA=,iv:jko2mOZYIJsVog6nN1vO3xyZBYJDgMcL4KuveP0Quak=,tag:VD20gC3CSW36buYaNmNB2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
