# Grafana admin credentials (copy from old grafana deployment)
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:TSFIgfw=,iv:P2e/+Lcq7BSBbg9pHmd5+5/eT/6cJLZZwG8Ka9BQE7I=,tag:I7iu0nY7bPRnnNwmF4rSCQ==,type:str]
  password: ENC[AES256_GCM,data:FYiuEOAL8rs/m8uhvu5e/hQjKeJ0nycGqa0YBQ==,iv:mDm9ZaW3sWpEDeqlnstAvU+FWH1eG1WQtqF+pH6cA90=,tag:klR871eD/DUyJTedy5Dmjw==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VEdnV3VTQjlDbURyeElr
        d1pYa05LaWl0U3I4aGppRklxZWczOVRiOFJnCjlEMlNOdlZpVGo0YkQrYlZnSUxt
        Y2xzTytOT0J1cG90WWdwRW9FOWdoQ1EKLS0tIDczT1cwZ2ZYQ3huTXdKSEd1TUJH
        OEM1c0tBL2daWC92UEFDTENMVTdkTDgKhUlSDGKKDclxfYzrTXkozRvVCLW30OaT
        RudKGAVgp3ohBvpa39lEjGBtuKVLHMjmvwxTVCeaYb6h3Bp4xqhu/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T02:27:43Z"
  mac: ENC[AES256_GCM,data:ieiK1dSyBCzsIL1a/CehahrMzCJZC0dv4sv2l977cOtROSg9rPExDEAFuyjBZBctqsC7xR//ToJcm+Bz1r8pbBH8dUXlzL4ji0LId6MHtscAMSNW0ny4tZkSo4nJH87hhBnJ+ucYDaYGujc7KdtBmMuD/meE6CAzB2PtsF6r4Hw=,iv:YG2qepCZ3OKMXPGPm9gpJbpdzicZPeQQx98j3ya1Wcw=,tag:p123e8RusadefMW6Du8o3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
# Grafana Authentik OAuth (copy from old grafana deployment)
apiVersion: v1
kind: Secret
metadata:
  name: grafana-authentik-oauth-client-secret
type: Opaque
stringData:
  client-id: ENC[AES256_GCM,data:QKHVJlhkQkORZ7A9j0yBLHCtqNC9DYre77cJGcjILugLBE3EhWdpkA==,iv:5pWTOW/MlELuFXrfI83+RT4rf342h/PZo+GU4gK057g=,tag:ExKknUh4iNRQXP2J/pKHNQ==,type:str]
  client-secret: ENC[AES256_GCM,data:jIBYAHV7s3iEwJ4G7UCTP+eCok1kBwcw/EV2U9j1Tb9iQFOF5hu3RDsQwCRwWexH2uIxvkeV36wOinmVgLWqfN/75Tqmuxbj7rrrWuPlxiqgW3L8f2HkvrAN5UkNGsQAtjDvVaYjW7d2PjzVGqnVmwy2GlVeFa6pL9QATSBFxPQ=,iv:GerHDD1TdbG7nJFMx/7u3F1WmSd0ZN23NOnj3JaIYuw=,tag:4y1V1EIROEJh4yH7zZ0KzA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VEdnV3VTQjlDbURyeElr
        d1pYa05LaWl0U3I4aGppRklxZWczOVRiOFJnCjlEMlNOdlZpVGo0YkQrYlZnSUxt
        Y2xzTytOT0J1cG90WWdwRW9FOWdoQ1EKLS0tIDczT1cwZ2ZYQ3huTXdKSEd1TUJH
        OEM1c0tBL2daWC92UEFDTENMVTdkTDgKhUlSDGKKDclxfYzrTXkozRvVCLW30OaT
        RudKGAVgp3ohBvpa39lEjGBtuKVLHMjmvwxTVCeaYb6h3Bp4xqhu/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T02:27:43Z"
  mac: ENC[AES256_GCM,data:ieiK1dSyBCzsIL1a/CehahrMzCJZC0dv4sv2l977cOtROSg9rPExDEAFuyjBZBctqsC7xR//ToJcm+Bz1r8pbBH8dUXlzL4ji0LId6MHtscAMSNW0ny4tZkSo4nJH87hhBnJ+ucYDaYGujc7KdtBmMuD/meE6CAzB2PtsF6r4Hw=,iv:YG2qepCZ3OKMXPGPm9gpJbpdzicZPeQQx98j3ya1Wcw=,tag:p123e8RusadefMW6Du8o3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
# AlertManager Telegram bot token
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram-secret
type: Opaque
stringData:
  bot-token: ENC[AES256_GCM,data:dmIBbLqPDWN1GmbJhQ1Ayk/sgxJmHJJsM3//NO9kAKv8vCDbkgfToLKEnUQKyg==,iv:aFMHRH+fcltzatLBJvcJN39OJi9EFX5zSjac/P6VZkE=,tag:aiGekrFlcHoetJOfut1nHA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VEdnV3VTQjlDbURyeElr
        d1pYa05LaWl0U3I4aGppRklxZWczOVRiOFJnCjlEMlNOdlZpVGo0YkQrYlZnSUxt
        Y2xzTytOT0J1cG90WWdwRW9FOWdoQ1EKLS0tIDczT1cwZ2ZYQ3huTXdKSEd1TUJH
        OEM1c0tBL2daWC92UEFDTENMVTdkTDgKhUlSDGKKDclxfYzrTXkozRvVCLW30OaT
        RudKGAVgp3ohBvpa39lEjGBtuKVLHMjmvwxTVCeaYb6h3Bp4xqhu/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T02:27:43Z"
  mac: ENC[AES256_GCM,data:ieiK1dSyBCzsIL1a/CehahrMzCJZC0dv4sv2l977cOtROSg9rPExDEAFuyjBZBctqsC7xR//ToJcm+Bz1r8pbBH8dUXlzL4ji0LId6MHtscAMSNW0ny4tZkSo4nJH87hhBnJ+ucYDaYGujc7KdtBmMuD/meE6CAzB2PtsF6r4Hw=,iv:YG2qepCZ3OKMXPGPm9gpJbpdzicZPeQQx98j3ya1Wcw=,tag:p123e8RusadefMW6Du8o3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
# AlertManager Deadman Switch CF Worker's Auth token
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-deadman-secret
type: Opaque
stringData:
  bearer-token: ENC[AES256_GCM,data:2UJAKusaX62CitXYGOLKY+VzcamnJPxnVPO7fwbuBTd2zNOe/j9aZZfBkgCTg3gk,iv:QCfbkjO2sdEB8YUyYc9kX1GJ4so+mS589WUMPjyvLBc=,tag:mfBubYO3+VXOZ66LDSOnBA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VEdnV3VTQjlDbURyeElr
        d1pYa05LaWl0U3I4aGppRklxZWczOVRiOFJnCjlEMlNOdlZpVGo0YkQrYlZnSUxt
        Y2xzTytOT0J1cG90WWdwRW9FOWdoQ1EKLS0tIDczT1cwZ2ZYQ3huTXdKSEd1TUJH
        OEM1c0tBL2daWC92UEFDTENMVTdkTDgKhUlSDGKKDclxfYzrTXkozRvVCLW30OaT
        RudKGAVgp3ohBvpa39lEjGBtuKVLHMjmvwxTVCeaYb6h3Bp4xqhu/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T02:27:43Z"
  mac: ENC[AES256_GCM,data:ieiK1dSyBCzsIL1a/CehahrMzCJZC0dv4sv2l977cOtROSg9rPExDEAFuyjBZBctqsC7xR//ToJcm+Bz1r8pbBH8dUXlzL4ji0LId6MHtscAMSNW0ny4tZkSo4nJH87hhBnJ+ucYDaYGujc7KdtBmMuD/meE6CAzB2PtsF6r4Hw=,iv:YG2qepCZ3OKMXPGPm9gpJbpdzicZPeQQx98j3ya1Wcw=,tag:p123e8RusadefMW6Du8o3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
