apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-people-refresh-api
type: Opaque
stringData:
  jellyfin-api-key: ENC[AES256_GCM,data:lZak0RWUE9W7qDw/yi9Xoe0MRzzJ47bEqzE2M0Pk/FM=,iv:jiT3yx2yXnZ+ATz/r4bDGvN6q/yrLZ0GR3kwvoWOMlw=,tag:ST4/Z7md9QQJLZeKl5486g==,type:str]
  jellyfin-xxx-api-key: ENC[AES256_GCM,data:Cd9Dh9TcyIM0Db7XkfTUuJIu1OyeF0TqtlKOzWL0HTI=,iv:o6GH3XZbC+MAsglFDhIndD0+n4d2MfNL/Bo06YUp7vE=,tag:IDHdUERpLP5yRPUtu9lu0w==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb3dxaFJ4R2g3Z2YyS0Zi
        dE5adHQ4QVNSbkxvSFpUMkYxWE5Pc29pZ0R3CklOYUMrdXQ1ZHpGMmRsTGRwL2Q1
        bEw3NzQxbjFpZFNzNk1uNnJ2QXphanMKLS0tIE5LRW4vcmUyaytUZ1cwVjlJSysw
        d29aMVZWcjdwaEk1V2EvYTJyLzQrVkUKY3OqLsjk7RRUXNXVDbTu+B8gVozw9tVX
        zqotd7We4bkCyQnno+5AIPDQpeffCE1d8vmxBKgbQAxWyqDaEz4jgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T19:52:11Z"
  mac: ENC[AES256_GCM,data:6fW5PWrQwdTjoTkafUUX5sZ3TWhHfAZ8xMAAKFE3sjuEF3J9EacfS9FKaGDREmS1FjopHcnKXhkbijcjbXZX5y4lsM21ynoZwx8ZtlF8/38euSgxp+pLJC95uvHUROVvU6HAWTu/eTS2CGDfIfdVKEhzNvylhzK3l7upcvjBdEI=,iv:oyL2O9puAAVsAowBCLYMvlTxo64xuFZlAYdTBnlvTJs=,tag:2D0dXIh73dcdnNDONwy/uQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
