---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: music-bot

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./ghcr-secret.sops.yaml
  - ./media-pvc.yaml
  - ./bot/ks.yaml
