apiVersion: v1
kind: Secret
metadata:
  name: sonarr-jellyfin-api
type: Opaque
stringData:
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:7aQTr+ByYiwgkOY6qqCvxz20KHqQFz9Jeh+ZC8mvlHQ=,iv:9mkRxzOl3MRvng0O3oOpqexKLURPyIxSolIObsdFkkg=,tag:mdDmw5ccFzeyb+LIyoYw+A==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeWI2NjM4Ynl0aE9IV2Rz
        NmZxbml1amx3MEdSY2hxbUlUamh1aTRyVlVFCnJmUEpjaUF0SC9LRnZ0Mk1oa3ht
        aG5qa244YVdXMFBtU0t2djVWdExMdUUKLS0tIE1RNjlBbUIxU2dlMjFiZjh0ZFBj
        S29ES2M0a0lHc0FtcnJMbjBwb2tLOWcKBWZEbSagYsJ+nXblhgJ4T5qQYT7tvFzW
        jkiI3SoiLzuZJcykluGgm9HDm3Y473hX5B8BiRlAFbb4hFOdtn9VeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T22:01:21Z"
  mac: ENC[AES256_GCM,data:Ku45edGI6IyTVDDS8l4vtLLDyDJm2zQepPQxKR0xLpv9xGs5cE1UedegETdzA3/chPo+Q+hp/nfK1M0jbI9CM9xVRKueUfzTTi8F7/YNJXUXWm9YAnfDU6DYldDtfTC4ayew+Q9h+Zb1BngeYiF+2GDN4MpyH/nCArxnZIBuB0A=,iv:GN+ili/T2kOx2h/amNxalIV9ObxCaMfP0eT5ifOK5L4=,tag:hDgaqoDwLPppyiOv14Jk1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
