apiVersion: v1
kind: Secret
metadata:
  name: slskd-soulseek-credentials
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:Rh8iwHFgCTRqtg==,iv:et7yoNcVa2pVIGddXiKZQSSigAtrEcQEza7GbPLIFhI=,tag:FduLUZNwr1Tqx1YMyOaYaw==,type:str]
  password: ENC[AES256_GCM,data:tfLzJu44eDu3R70T/jU5ns2h+jQmglazZ4n4LNrmx4ZWbWSJ7D+vIfzyr8f3auDh,iv:dnCiuLZf0z2RvRtL1WVoOwmSP8j/Wj+iCbnQAVXkJ7I=,tag:NncRrYcmlzIb/5pjEB9blA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cmhsZ0FnbWVUQXdwTzUz
        M0xqY3Q3L3JvNlpqRk1ZclowMnNWL3hmenpnCmVUa3F2bE1KdUxEZXI1MkZORWYy
        d0lFcHd3S2NPUFFOMXNxSDlLb2lndm8KLS0tIHdjSjl5ZFVaZzZuejhiejVBbE5o
        cnZ3YXRQZmtCVW1LZEw1bW1sRXUvSmMK5ex+fmYhRSLoV4yvt+jbxZTvJPT6r9ZK
        Byu5vEqqBvZC5ec3JZKUe50j9XFbvXhhLi6XGR/7OnE9nAeQ47MyLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:44:01Z"
  mac: ENC[AES256_GCM,data:Pjki0D0RRsY0pNOkBOs7LBPbagZKItyVP1v6GlxC3Hcg5ObqZTgFrc4dQ0ANxjF+LqGOaADU5E8c85r3TuQ/yD5lLbEUF7ySRR4ya8DfMqxcIhufJdFJRKyOIORIG5xgovuTaT0sa3tGoir+txpKewiX4qeARb5PwMlwrP4oUQs=,iv:n+zLUg1Z4m1Nv2kCyEGFIXw/Z4gCqT1yZnOPnDt+anY=,tag:IoJvU7BVNJixo4G6Z54YVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: slskd-api-key-soularr
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:OuFM8tzNJa6VLIXt9Q4hA/yupxYcBY+mdeJU0CDn4Jb0+ACB7rZEZq8AKRd3wJC/,iv:XkRFnLtJZ0ajpyEoMTp6NwVbhsvYQ0qloNbzXWpqsmk=,tag:lwtCNhHXLQ+CJMWV22sZIA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cmhsZ0FnbWVUQXdwTzUz
        M0xqY3Q3L3JvNlpqRk1ZclowMnNWL3hmenpnCmVUa3F2bE1KdUxEZXI1MkZORWYy
        d0lFcHd3S2NPUFFOMXNxSDlLb2lndm8KLS0tIHdjSjl5ZFVaZzZuejhiejVBbE5o
        cnZ3YXRQZmtCVW1LZEw1bW1sRXUvSmMK5ex+fmYhRSLoV4yvt+jbxZTvJPT6r9ZK
        Byu5vEqqBvZC5ec3JZKUe50j9XFbvXhhLi6XGR/7OnE9nAeQ47MyLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:44:01Z"
  mac: ENC[AES256_GCM,data:Pjki0D0RRsY0pNOkBOs7LBPbagZKItyVP1v6GlxC3Hcg5ObqZTgFrc4dQ0ANxjF+LqGOaADU5E8c85r3TuQ/yD5lLbEUF7ySRR4ya8DfMqxcIhufJdFJRKyOIORIG5xgovuTaT0sa3tGoir+txpKewiX4qeARb5PwMlwrP4oUQs=,iv:n+zLUg1Z4m1Nv2kCyEGFIXw/Z4gCqT1yZnOPnDt+anY=,tag:IoJvU7BVNJixo4G6Z54YVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
