---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: envoy-external
spec:
  endpoints:
    - dnsName: "external.${SECRET_DOMAIN}"
      recordType: A
      targets: ["${SECRET_PUBLIC_IP}"]
