apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-credentials
type: Opaque
stringData:
  S3_ACCESS_KEY: ENC[AES256_GCM,data:Ttw7QiHKnix3UVBGfeEcBVkpGCTrgxlIcw==,iv:QOZuiCp3Ta8vKveKQRZmdGYOVSRqkU2BRuEzI7sr/WY=,tag:wseZwr1TbXF5xrw5LP0ahA==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:CesufnvrQoN9lG8cjvXXDzRts5j/CeyPK8CDFBa4Kja3VYEIhLFA3g==,iv:/6pHJ18MgI7Q0cBoHT3LKy1dm6tnlShloOW3WZEp4uw=,tag:Oi+IYfBXxzNO19NODYJ2Cg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNVJtVFZjSnprbjI0QkE0
        UmpnZEpKaEFGZDhXdVg1OGlTT1dJRjFNYUJzCjV1OEd0ZFBLS2lMMkF5TjNHRkls
        TWRUV2YxLzBLekNwODF1bUR4OUZZWXcKLS0tIGp1M1RsVlNxZzcvUlZsV3NTN1pY
        YWtVa3pZWlQ3V0cwZXcwSElrdjVHSFkKnhucbZ6wmOS/ON32/bBEDmJ3GfIQeAnx
        AAEK/zqbJQ5x8d9vGdEDQStyjqPSjnwTkQEnz34g+/1z0BuMrDH/0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T15:34:12Z"
  mac: ENC[AES256_GCM,data:VqCN/V8HO6ntFFc/Jj5zDn3TBDeVuztAZZIvOscqVvsMOrpEpO6pIxdiUSd+UhlWFMls3I/d5nhtD+jVqXQzleBu70te2MUHahTlH5uvNSVFBzfYj0E2kSAcPUL/EK1MBNmsPN5hnSybURO7bSm62/eUu+RrZXTdiBmmTAfms20=,iv:bUESR6xGG0vy3jqNBQ9g71B5aQqCcG/9mnWKz3dgIwk=,tag:KdkqAMoq+RPKLoI6stVPiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
