---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./prometheusrule-storage.yaml
  - ./prometheusrule-radarr.yaml
  - ./prometheusrule-sonarr.yaml
  - ./prometheusrule-lidarr.yaml
  - ./prometheusrule-prowlarr.yaml
  - ./prometheusrule-bazarr.yaml
  - ./prometheusrule-sabnzbd.yaml
  - ./prometheusrule-qbittorrent.yaml
  - ./prometheusrule-jellyfin.yaml
  - ./secret.sops.yaml
