apiVersion: v1
kind: Secret
metadata:
  name: metrics-exporters-secret
type: Opaque
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:pe2Mf8VQ9ym/JG2NemZvg0F61iVXhopW87zyYHGkZrM=,iv:wVfYJRvYy+/2hE5rvjWrAeeO8EmjAHAU9s1ihbGUV1E=,tag:nGMdtEoEHENdrfa1TnVzsA==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:hhFiUBvRo+ulWBGZ3MJZ2bZIcTvzdnG//xwTayOaeME=,iv:6qKERK4cDNMRxSawFyaIC7nik9HIbBudRbIwygpup4U=,tag:ANFp1lOR/RNeUqxcx3Zlkg==,type:str]
  LIDARR_API_KEY: ENC[AES256_GCM,data:bw+AKn9Lp7x5bqrvDSbVGAj8mbYi9bMQqWL+fDBCXhI=,iv:U9zQCIe/olMBG3M93GXlkaUAT/N0Nea5hPU0cG63Fd8=,tag:lyBAxEHfsdzz2Q2iPpm83w==,type:str]
  PROWLARR_API_KEY: ENC[AES256_GCM,data:G0A5HPNDkClEEHSNd6NcwQmhtNA7+ownSP0to/astHo=,iv:6S5tCkEWOCvz3FjcTI7GJGHKgcGchuJNAs7/vdHUuC4=,tag:CGqcwSdCkpqJL+HAOKKymA==,type:str]
  BAZARR_API_KEY: ENC[AES256_GCM,data:67M/qU0Wo/LqSsbLujOn9/EBa+81kjCth+SxUtQHHdw=,iv:VaaP6KwGd1HyYl+/Q7DheQzybFbUB9IIcIVRXpLl3UA=,tag:z45CT3vFiAC7opeNijLIjg==,type:str]
  SABNZBD_API_KEY: ENC[AES256_GCM,data:BcbJjIpB8xzSabn/2La1Kq3VVyAfPCcZc5rEgqLmBOw=,iv:demrh3Y6KUoxZqiRSA80FqGwlQCi26K9EQZX9w6HV7k=,tag:kSMEUN/YA7OuB7N43QvDJw==,type:str]
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:P9KWjUaBjUaDe2ZflcuLG8l0LgASG07G1Qusu7p3UPI=,iv:D/PdShhQvymvDQUuNnQ6ju26Z5B2oVfp/I9X2zyacEs=,tag:9Xcd2xs1v+wnyFdRebNBcg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZlJSZjF2SkFiSFRUKyt0
        U1hqOC9yd21ZL0paeG5UcmtiRTlyQ0t3RzJjCjZ2eW43MlZjaVV2b0syZUR6dEg3
        M0c4eEx2dmkxNmdpMGxWRy92RVI3cUkKLS0tIG5yR0UzOUYrYmlJNnpZdVppVzFo
        QVUwMDAwQ2VLWXM2UUtDSEYxNHNHNWcKlpD5I2KGzj/Lv8T/3MQmk4yoEY4t+gKp
        R27t2FetV0GDuzP6IMKcsvBbKlXiGwj0j1eaEJTrBBZMpePBxe/i1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-22T01:16:46Z"
  mac: ENC[AES256_GCM,data:ghuABmW3zxkwuM+1+SeBXEG14d14GU2Ik0QQ05ihm7mcf7US7bUEtj+seqgNfAhY1R/KC7YSmvDTbEIUlCji282sfuZbchBVDkfQq8TPtmwmUFxhYA/i9HvXR/CdspE7KUbKat+Nje74D0AXT/WRDgB/iL2DWUy8wz5sH2nwsA0=,iv:TWRUHFilfER/QBK1PGn2ILNuNLh/TxCKHRSErGcqwV0=,tag:M375WIXMKqnFsefk38LfDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
