apiVersion: v1
kind: Secret
metadata:
  name: lidarr-exporter-secret
type: Opaque
stringData:
  LIDARR_API_KEY: ENC[AES256_GCM,data:aUZrgDkeh+K02gkENB2M+71qp5Sx6QxWWLrS9dptPb4=,iv:IVtrFIUOwBDOsnwuyN7TGGIVcwtjCe/1SeYEtjfJZsU=,tag:dj0FFZWuFZLBDwLpq8w9yg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd29jL2svTVdmd3o2Q1Z3
        YnJIaG9NZStpQjRmTjgrbFhWTm81WVUzL1ZzCnZCQzNZcmVsQkt3dGRuTFNUb3NM
        N1NYV09JVVh0QUdpNXJxY1BsU0dOb2cKLS0tIDhTZlFFdXBnbFdsYVVUejEvM25J
        SmZlamNJTVMxK05UK01aNHBBdzNCdUkKUIilrd+sGXSOXZ0GHURaEbNWR71kM0lz
        MfpalPi2RW7cx2y6b7ODxSS6HlLTiwEr7mGGRuPwodlt04rMBeNmNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T23:31:25Z"
  mac: ENC[AES256_GCM,data:Ar6EBBra67L8M3t1L6UNXFW3zxMO9ryaZ/t4Jhed2cYMX7k6S4UXxohJ++aV74JyFenIZOeQLKWCqnGJ1WzbbvgbjxDqJfWyioZVhcSw+GKQQbZ4AfJYWbfr4FK9+h+2VN/crTYBeKDsZwTGgKlFh9GiZajomyJV6tj429IgogY=,iv:dKjqWyfPNCi8BZN1VsgPRi3vr9nEp6pB3+tNuSuhd24=,tag:MBBOD4Fx9CBcnq8cQG8/Dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
