---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homeserver-subnet
spec:
  subnetRouter:
    advertiseRoutes:
      - 192.168.3.102/32 # envoy-internal
      - 192.168.3.110/32 # adguard home
