---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homeserver-subnet
spec:
  subnetRouter:
    advertiseRoutes:
      - 192.168.3.26/32 # homeserver-main (envoy-internal + adguard-home)
