---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  chart:
    spec:
      chart: tailscale-operator
      version: 1.80.3
      sourceRef:
        kind: HelmRepository
        name: tailscale
  interval: 1h
  values:
    operatorConfig:
      hostname: homeserver-ts-operator
      defaultTags:
        - tag:k8s-operator
      logging: info
    proxyConfig:
      defaultTags:
        - tag:k8s
    oauthSecretVolume:
      secret:
        secretName: tailscale-operator-oauth
