apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-oauth
stringData:
  client_id: ENC[AES256_GCM,data:s6D2qEIVTjyPENaIQRz0qHQ=,iv:w5jipcxi+Td9uy+ivMfmNwtkp0bcIbMt6vOCgavoi8A=,tag:eoy7R8N2iKj4MWK2MRVkRA==,type:str]
  client_secret: ENC[AES256_GCM,data:UhwWIIxRS16bpXCXkCYRqkGm8OIESPdEq0Q69MX+U7nO7ls92oMBthPYG3R+uUQsNMnI1T0MS0dwrDSHWun2iQ==,iv:yDP5PB33gQSQxTvqLl0mnt5lwoYr9dY0UTUnC5G1X7I=,tag:vGMpcQL5BqPhFuZAovyEQA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN1Qxc2hFc3BSNFpjVWx5
        R0x0WnZSVytSbHZnWVhlcU1IOVZOSlBXS1IwCi9SdXFLMzc5S0lGWmhmVnBJKytT
        V3V6SFNXWHFGV2JaY2dsSDdCelVTWEUKLS0tIFkyRXNENFo0YUEyNGZUUDJoUExr
        WTBmdGNUc2ZZaVQ0TVk2U0dPeHFqK0UKLu56h7JtSZa34v3JGJMfMl1O2Iuftb02
        XMKz+sq/uyGZZyM/SUq3luzA3e+1p+gHFmIohfu6HDJUnJ6r99yfEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T00:03:35Z"
  mac: ENC[AES256_GCM,data:N0B9z/7xbMDYSQWVGejK5DUKx0vYRKppTvutwSM6cT6fs0nFx0tgOvqYp+0Sp5GG75nN2ptA8opPepJmcZdP66BNlvUoHOZ4cvDKZHBila7mj3FcVLuWzWAUJRwlP1YPjh3HujNMU2g018/MEUU4JH9qSGfxisXBNwcBAGeQWbU=,iv:12EG1WDKQm/1RRPGe62mbFEsCZXhw3MieW9/q1wX79o=,tag:F94oEqIZvTrr6MdnhvshbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
