---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./flux-system/kustomization.yaml
  - ./kube-system/kustomization.yaml
  - ./network/kustomization.yaml
  - ./authentik/kustomization.yaml
  - ./cert-manager/kustomization.yaml
  - ./default/kustomization.yaml
  - ./monitoring/kustomization.yaml
