---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: qbit-manage-config
    files:
      - config.yml=./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true
