apiVersion: v1
kind: Secret
metadata:
  name: backrest-secret
type: Opaque
stringData:
  RESTIC_PASSWORD: ENC[AES256_GCM,data:pWpFS+2i4ZkIQ5Rhyv3NA0vRdqtagcKPjXta6xI1XezFw/QJaDBGAmsKah00sBnm,iv:CoLyKYZYZJ/lX3YzYFwAeifkRKn3gxeSBCwvypb+WJ0=,tag:8qDOQqbuwCJhI7XmHEdbwA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JhTi1fTfNgSEcvpwyewSW5fQk3WHGFTlvQ==,iv:IHwDC/fKPgh2j/NIrwheAvfOXOTxSlfQGGxSy5WK4DA=,tag:wZjx2MQ1MMLkJJ8OaX4yWw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2mwKvpVOdF9dzpDQ6oUgSCoDr3Qc/kOqr2oZ+AJWfuoE5QVHPJw0Ng==,iv:qHDp4X+YoyBgt/53UWr8YX6lZJ4RxiQet7SOprb2E4g=,tag:SOFk48LrBqnVYGna0qUPEA==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNHR6S3IyQXN5RnZ4WnVU
        R3FlbTY4WVVtV1JvcXpUS29GdS9xa1dDUDFFCkZmTkhmM0NkMlRlN3V6MTYwMlVL
        UE1Eb1phTEg5M0FLRTJzb2RrdmsyclEKLS0tIGdHdkZiN2c3MC9ZNTRtZVZGOXFJ
        SUZqZGFydnNCei92Q3dMOHNkTFhvelkKj2dFjm1ecnDXoc4YVqc1UHwT2Hwai9mf
        r/p7RJzOLJatUgu1g2oMS/qbNBAknoPMC9JRy6CFiZN6YFKzUprQBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T22:23:41Z"
  mac: ENC[AES256_GCM,data:yjpoV8VyhSCPseAbY4d3egXMJkLOtK8nSEMQ05uDVDqcNnWlC84eFQAszN28c6Pms3tc0yFNfrhL7a0+JiZs4i5FH7Ju8RMVNKS3BB7l7dYH+j+F1bfLisGB7aDgRAf0Sp77BDLafVRK8gyoPd33Ya2Txf1QpUzZzdDa71SIGq0=,iv:ah7CcMyEm/Zmn85rVdIaqkXh5C3RppbHZqy/wOLz2pE=,tag:12Qh8JcklzPIxmAa423CCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
