---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: music-bot
spec:
  interval: 1h
  path: ./kubernetes/apps/music-bot/bot/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: music-bot
  wait: false
