apiVersion: v1
kind: Secret
metadata:
  name: github-container-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:rh4Y1yPEMepkbSezP/k0vJVSrG5HVmiCa7hnnAsVLbo1gP2uIFGAu+qiu1y+MnPZX0yPcHsy1MySJoQrcDOz6dbPvyIF3riUQvWpsmxC8tZov2Pl2NpmkngBJrmYV15O265xqx6KnPJgCgEcqgpk2avB2nuDj8vFAs0WrT/T49ON9HGxcCOB4Qdkz1HEVzsdMZWW/RkBorMyD5CF3yti+kxM8K5sAxd1wlu9kkH5LUyRrFk=,iv:XdPYsvqXvvSc2okj6HdFusymsMwFDR63OaOBqe41GRE=,tag:Vs3wjLD6i1+5yl4V5bGr/A==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTDBqZ1N4WndJcVZteklQ
        QVJ6MXFJcW9sZkFHQldyUXVreUtxN0JqY3hnClJCbDFvZm1mNnlrRE9STlJ4RVlM
        QytoWDk0OWp5dnFXb2lCS0IzMG9QUjQKLS0tIFNxN0VZeWlKbzg4OWx2MFJyWGN6
        a0wwWENHcEN1elQydHI3Qm5FQmI1QTgKhJ25wHe5CQZ6LSXBXKPIo5KNyO0Um7ke
        KndoBIEfn+bPMQOxl8ptp4V/P3Mh+x5Hp4c+jz5iAjIp0jDZJj2uKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T22:52:03Z"
  mac: ENC[AES256_GCM,data:cAZhPfmoK0OXTWKjDM/ZP9TsYFN/uloosL7sGFGzNb/jzPMhiJ1AuOd9E8pr5u+L4BNFYdN6XrqtESW/FyqC2SwGx6A11x2cUe3bQOVytwI3+fT0W6+6ddBMK+Xw2CwTo+DOCpB/xdq2lwEl41jqGkpw+BSlqQeJxnx60JgzWpo=,iv:YA2GCHCX2kLSusUmYkzI7T5Ac+f6ZyA78QUJbQppVCo=,tag:FG9YlW6CLhcogF8qgKRcEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
