apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-exporter-secret
type: Opaque
stringData:
  PROWLARR_API_KEY: ENC[AES256_GCM,data:XrnqTP9yZXkIRH3YvwwNAk5KQb/EL8QjjARDdZAydlM=,iv:wyrWREblkkyVPy6pxYgq3GV6FXgwPc51EE3DOK3V/mY=,tag:8ca7IoBwi3znaKJvErxihg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNXdYY0VLWTN6TGNJRlMx
        eEtYbE1SVzFLcGRRb0JmTlUyVHpGRXNFWkZJClVtU0R4KzE0QjF4MHFPemJ0VXJD
        TmJ5SmNCL1VJWFNoUk9xRW1EaVB5WjQKLS0tIFBTM2ZhUHdrUXBaTUR0RFU3eDFp
        RFMwQyt0eUc4eVR5VUI4S2x1eU9lbm8KXegT8iRRyz4/Ee2aqOy+ZH2CvtxTCdnq
        JraVC4KtaoGYdhKtHK3aArI9MFDL3v2akqiyJC1JOhjGsucnOLytcQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T23:31:30Z"
  mac: ENC[AES256_GCM,data:M0VKadiNu/+rYTm1dH97uI6ZTQ4Klo+SUOo23Gn2qXIofzw2u3PiIyq+EvnEm4vB54423/vkaRiGko4ftYYeOKnl8iVokyNxU8brh7lZEl+o4dPQKFw8nW2hagt/qXCAS1xszDJhe/z1Aj7CjSCPD9SKQwf3RogvR2WC/Js0xbE=,iv:WA7T6dzt4OOhMTBPK76akhJisjYlVPN55UTfspeYESU=,tag:pNWzqHyQ+6Cq2lxNdS/r1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
