---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./cloudflare-dns/ks.yaml
  # - ./cloudflare-tunnel/ks.yaml  # Replaced by Tailscale
  - ./envoy-gateway/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./tailscale-dns/ks.yaml
  - ./tailscale-operator/ks.yaml
