---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./network-secrets.sops.yaml
  - ./adguard-home/ks.yaml
  - ./cloudflare-dns/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./tailscale-operator/ks.yaml
  - ./arping/ks.yaml
