apiVersion: v1
kind: Secret
metadata:
  name: network-secrets
stringData:
  SECRET_NEXTDNS_PROFILE_ID: ENC[AES256_GCM,data:Drek8p+T,iv:fdB+TutIL7fYaT0XuzhzQ1ll2NVqgHqtR0nNugNK22Q=,tag:eVvq3Z2/QiftKI256qEgIw==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc3dCZFZ1VTFaWEtuRXg5
        cTNrWTR4Wk9IN2Q1UFQ4dGZ1eFV2Mzg2RDJzCkZuWm5lajVmWTBWbng1aGMwRjBH
        d09uQWZIUVYwWVZNZHhubFRTbWo0b3cKLS0tIE02bVByam5xcUl4elAzb2drTHZX
        OUdUY0s3OWk4ZnROT3VDZDJZQWZ1MW8KUUFbMpnM50ORjahjZWdPgVcrCFZoOeV/
        waE9Cy9S4X1VGTuRR0T81AHcgbsz+8QV7QZQ3qWdWvUHB1Bwiry/GA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T02:27:09Z"
  mac: ENC[AES256_GCM,data:EYxUpybv6/7PAbEGoBZowTa8ETzLYZgN1g+AEGOvHQd9z49adWlAOyHHX6KJzKy1eTvDmitqcJk4JmOhp73heB/CFTEj8dzZy8FXLsPL3RF4xQWONNJmOBB+4h+jN1n+9drcgXqdufcs6JPkrn9GWtUvYU9jbFXbJMCLW3Ar5Os=,iv:EaEvH92i55+hHNfHn2GyuMgfob2tRrtikdfjS5DhXEM=,tag:zy70KIGPXO5uK//baYyo0w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
